DECLARE
FUNCTION parse_month(p_month_str IN VARCHAR2) RETURN VARCHAR2 IS
BEGIN
CASE LOWER(p_month_str)
WHEN 'sty' THEN RETURN '01';
WHEN 'lut' THEN RETURN '02';
WHEN 'mar' THEN RETURN '03';
WHEN 'kwi' THEN RETURN '04';
WHEN 'maj' THEN RETURN '05';
WHEN 'cze' THEN RETURN '06';
WHEN 'lip' THEN RETURN '07';
WHEN 'sie' THEN RETURN '08';
WHEN 'wrz' THEN RETURN '09';
WHEN 'paź' THEN RETURN '10';
WHEN 'lis' THEN RETURN '11';
WHEN 'gru' THEN RETURN '12';
ELSE RETURN '01';
END CASE;
END;
PROCEDURE add_p (
p_first IN VARCHAR2,
p_last  IN VARCHAR2,
p_dob   IN VARCHAR2,
p_nat   IN VARCHAR2,
p_pos   IN VARCHAR2,
p_num   IN NUMBER,
p_h     IN VARCHAR2,
p_foot  IN VARCHAR2,
p_team  IN VARCHAR2
) IS
v_dob   DATE;
v_join  DATE;
v_h     NUMBER;
v_f     VARCHAR2(10);
v_d_d   VARCHAR2(10);
v_d_m   VARCHAR2(10);
v_d_y   VARCHAR2(10);
v_pos   VARCHAR2(20);
v_mem_id NUMBER;
v_c_id   NUMBER;
BEGIN
v_pos := NVL(SUBSTR(p_pos, 1, 20), 'Nieokreślona');
BEGIN
v_d_d := SUBSTR(p_dob, 1, INSTR(p_dob, ' ') - 1);
v_d_m := SUBSTR(p_dob, INSTR(p_dob, ' ') + 1, 3);
v_d_y := SUBSTR(p_dob, INSTR(p_dob, ' ', 1, 2) + 1);
v_dob := TO_DATE(v_d_y || '-' || parse_month(v_d_m) || '-' || LPAD(v_d_d, 2, '0'), 'YYYY-MM-DD');
EXCEPTION WHEN OTHERS THEN
v_dob := TO_DATE('2000-01-01', 'YYYY-MM-DD');
END;
v_h := TO_NUMBER(REPLACE(REPLACE(REPLACE(p_h, 'm', ''), ',', ''), '-', '0'));
IF v_h IS NULL OR v_h = 0 THEN v_h := 180; END IF;
IF INSTR(LOWER(p_foot), 'praw') > 0 THEN v_f := 'Prawa';
ELSIF INSTR(LOWER(p_foot), 'lew') > 0 THEN v_f := 'Lewa';
ELSE v_f := 'Obie';
END IF;
BEGIN
SELECT club_id INTO v_c_id FROM Team WHERE name = p_team;
EXCEPTION WHEN NO_DATA_FOUND THEN
RETURN;
END;
v_join := SYSDATE - DBMS_RANDOM.VALUE(0, 2555);
INSERT INTO Member (first_name, last_name, date_of_birth, nationality, join_date, phone, email)
VALUES (
NVL(p_first, p_last),
NVL(p_last, p_first),
v_dob,
p_nat,
v_join,
TO_CHAR(ROUND(DBMS_RANDOM.VALUE(100, 999))) || ' ' ||
TO_CHAR(ROUND(DBMS_RANDOM.VALUE(100, 999))) || ' ' ||
TO_CHAR(ROUND(DBMS_RANDOM.VALUE(100, 999))),
LOWER(REPLACE(p_first, ' ', '')) || '.' || LOWER(REPLACE(p_last, ' ', '')) || '@gmail.com'
)
RETURNING member_id INTO v_mem_id;
INSERT INTO Player (member_id, position, shirt_number, height, weight, preferred_foot, club_id)
VALUES (v_mem_id, v_pos, NVL(p_num, 0), v_h, ROUND(DBMS_RANDOM.VALUE(60, 90)), v_f, v_c_id);
INSERT INTO Contract (contract_id, start_date, end_date, salary, status, player_id, club_id)
VALUES (seq_contract_id.NEXTVAL, v_join, SYSDATE + DBMS_RANDOM.VALUE(0, 1095), ROUND(DBMS_RANDOM.VALUE(5000, 50000), 2), 'ACTIVE', v_mem_id, v_c_id);
END;
BEGIN
add_p('Bartosz', 'Mrozek', '23 lut 2000', 'Polska', 'Bramkarz', 41, '1,94m', 'prawa', 'Lech Poznań');
add_p('Filip', 'Bednarek', '26 wrz 1992', 'Polska', 'Bramkarz', 35, '1,88m', 'prawa', 'Lech Poznań');
add_p('Mateusz', 'Mędrala', '3 sty 2006', 'Polska', 'Bramkarz', 31, '1,89m', 'prawa', 'Lech Poznań');
add_p('Alex', 'Douglas', '17 sie 2001', 'Szwecja, Ghana', 'Środkowy obrońca', 3, '1,90m', 'prawa', 'Lech Poznań');
add_p('Wojciech', 'Mońka', '18 sty 2007', 'Polska', 'Środkowy obrońca', 90, '1,88m', 'prawa', 'Lech Poznań');
add_p('Antonio', 'Milic', '10 mar 1994', 'Chorwacja', 'Środkowy obrońca', 16, '1,90m', 'lewa', 'Lech Poznań');
add_p('Filip', 'Dagerstal', '1 lut 1997', 'Szwecja', 'Środkowy obrońca', 25, '1,89m', 'prawa', 'Lech Poznań');
add_p('Bartosz', 'Salamon', '1 maj 1991', 'Polska', 'Środkowy obrońca', 18, '1,94m', 'prawa', 'Lech Poznań');
add_p('Maksymilian', 'Pingot', '1 kwi 2003', 'Polska', 'Środkowy obrońca', 55, '1,88m', 'lewa', 'Lech Poznań');
add_p('Maciej', 'Wichtowski', '2 sty 1991', 'Polska', 'Środkowy obrońca', 50, '1,85m', 'prawa', 'Lech Poznań');
add_p('Michał', 'Gurgul', '30 sty 2006', 'Polska', 'Lewy obrońca', 15, '1,82m', 'lewa', 'Lech Poznań');
add_p('Elias', 'Andersson', '31 sty 1996', 'Szwecja', 'Lewy obrońca', 85, '1,78m', 'lewa', 'Lech Poznań');
add_p('Joel', 'Pereira', '28 wrz 1996', 'Portugalia', 'Prawy obrońca', 2, '1,78m', 'prawa', 'Lech Poznań');
add_p('Ian', 'Hoffmann', '8 wrz 2001', 'Stany Zjednaczone, Niemcy', 'Prawy obrońca', 91, '1,75m', 'prawa', 'Lech Poznań');
add_p('Antoni', 'Kozubal', '18 sie 2004', 'Polska', 'Defensywny pomocnik', 43, '1,77m', 'prawa', 'Lech Poznań');
add_p('Jesper', 'Karlström', '21 cze 1995', 'Szwecja', 'Defensywny pomocnik', 34, '1,85m', 'prawa', 'Lech Poznań');
add_p('Stjepan', 'Loncar', '10 lis 1996', 'Bośnia i Hercegowina, Chorwacja', 'Defensywny pomocnik', 20, '1,87m', 'lewa', 'Lech Poznań');
add_p('Radosław', 'Murawski', '22 kwi 1994', 'Polska', 'Defensywny pomocnik', 22, '1,73m', 'prawa', 'Lech Poznań');
add_p('Gísli', 'Thórdarson', '12 wrz 2004', 'Islandia', 'Defensywny pomocnik', 23, '1,91m', 'prawa', 'Lech Poznań');
add_p('Sammy', 'Dudek', '18 kwi 2008', 'Polska, Niemcy', 'Defensywny pomocnik', 53, '1,75m', 'prawa', 'Lech Poznań');
add_p('Igor', 'Brzyski', '15 mar 2007', 'Polska', 'Defensywny pomocnik', 80, '1,88m', 'obie', 'Lech Poznań');
add_p('Rasmus', 'Carstensen', '10 lis 2000', 'Dania', 'Prawy pomocnik', 29, '1,83m', 'prawa', 'Lech Poznań');
add_p('Afonso', 'Sousa', '3 maj 2000', 'Portugalia', 'Ofensywny pomocnik', 7, '1,74m', 'prawa', 'Lech Poznań');
add_p('Filip', 'Jagiełło', '8 sie 1997', 'Polska', 'Ofensywny pomocnik', 24, '1,79m', 'prawa', 'Lech Poznań');
add_p('Tymoteusz', 'Gmur', '2 sty 2008', 'Polska', 'Ofensywny pomocnik', 44, '1,74m', 'prawa', 'Lech Poznań');
add_p('Kristoffer', 'Velde', '9 wrz 1999', 'Norwegia', 'Lewy napastnik', 57, '1,79m', 'prawa', 'Lech Poznań');
add_p('Daniel', 'Håkans', '26 paź 2000', 'Finlandia', 'Lewy napastnik', 11, '1,78m', 'prawa', 'Lech Poznań');
add_p('Kornel', 'Lisman', '20 lut 2006', 'Polska', 'Lewy napastnik', 56, '1,86m', 'prawa', 'Lech Poznań');
add_p('Ali', 'Gholizadeh', '10 mar 1996', 'Iran', 'Prawy napastnik', 8, '1,75m', 'lewa', 'Lech Poznań');
add_p('Patrik', 'Walemark', '14 paź 2001', 'Szwecja', 'Prawy napastnik', 10, '1,84m', 'lewa', 'Lech Poznań');
add_p('Filip', 'Szymczak', '6 maj 2002', 'Polska', 'Prawy napastnik', 60, '1,87m', 'prawa', 'Lech Poznań');
add_p('Dino', 'Hotic', '26 lip 1995', 'Bośnia i Hercegowina, Słowenia', 'Prawy napastnik', 21, '1,68m', 'lewa', 'Lech Poznań');
add_p('Adriel', 'Ba Loua', '25 lip 1996', 'Wybrzeże Kości Słoniowej', 'Prawy napastnik', 6, '1,70m', 'lewa', 'Lech Poznań');
add_p('Mario', 'González', '25 lut 1996', 'Hiszpania', 'Środkowy napastnik', 77, '1,83m', 'prawa', 'Lech Poznań');
add_p('Mikael', 'Ishak', '31 mar 1993', 'Szwecja', 'Środkowy napastnik', 9, '1,85m', 'obie', 'Lech Poznań');
add_p('Bryan', 'Fiabema', '16 lut 2003', 'Norwegia', 'Środkowy napastnik', 19, '1,83m', 'prawa', 'Lech Poznań');
add_p('Kacper', 'Trelowski', '19 sie 2003', 'Polska', 'Bramkarz', 1, '1,93m', 'obie', 'Raków Częstochowa');
add_p('Muhamed', 'Sahinovic', '30 wrz 2003', 'Bośnia i Hercegowina', 'Bramkarz', 31, '1,91m', 'prawa', 'Raków Częstochowa');
add_p('Dusan', 'Kuciak', '21 maj 1985', 'Słowacja', 'Bramkarz', 12, '1,94m', 'prawa', 'Raków Częstochowa');
add_p('Stratos', 'Svarnas', '11 lis 1997', 'Grecja', 'Środkowy obrońca', 4, '1,86m', 'prawa', 'Raków Częstochowa');
add_p('Ariel', 'Mosór', '19 lut 2003', 'Polska', 'Środkowy obrońca', 2, '1,84m', 'prawa', 'Raków Częstochowa');
add_p('Bogdan', 'Racovitan', '6 cze 2000', 'Rumunia, Francja', 'Środkowy obrońca', 25, '1,87m', 'prawa', 'Raków Częstochowa');
add_p('Zoran', 'Arsenic', '2 cze 1994', 'Chorwacja', 'Środkowy obrońca', 24, '1,88m', 'prawa', 'Raków Częstochowa');
add_p('Matej', 'Rodin', '13 lut 1996', 'Chorwacja', 'Środkowy obrońca', 88, '1,94m', 'prawa', 'Raków Częstochowa');
add_p('Milan', 'Rundic', '29 mar 1992', 'Serbia', 'Środkowy obrońca', 3, '1,88m', 'lewa', 'Raków Częstochowa');
add_p('Kamil', 'Pestka', '22 sie 1998', 'Polska', 'Lewy obrońca', 78, '1,89m', 'lewa', 'Raków Częstochowa');
add_p('Gustav', 'Berggren', '7 wrz 1997', 'Szwecja', 'Defensywny pomocnik', 5, '1,87m', 'prawa', 'Raków Częstochowa');
add_p('Vladyslav', 'Kochergin', '30 kwi 1996', 'Ukraina', 'Defensywny pomocnik', 30, '1,78m', 'prawa', 'Raków Częstochowa');
add_p('Péter', 'Baráth', '21 lut 2002', 'Węgry', 'Defensywny pomocnik', 23, '1,85m', 'prawa', 'Raków Częstochowa');
add_p('Ben', 'Lederman', '8 maj 2000', 'Polska, Izrael', 'Defensywny pomocnik', 8, '1,78m', 'lewa', 'Raków Częstochowa');
add_p('Szymon', 'Czyż', '8 lip 2001', 'Polska', 'Defensywny pomocnik', 53, '1,76m', 'prawa', 'Raków Częstochowa');
add_p('Vasilios', 'Sourlis', '16 lis 2002', 'Grecja', 'Środkowy pomocnik', 62, '1,83m', 'prawa', 'Raków Częstochowa');
add_p('Fran', 'Tudor', '27 wrz 1995', 'Chorwacja', 'Prawy pomocnik', 7, '1,73m', 'prawa', 'Raków Częstochowa');
add_p('Michael', 'Ameyaw', '16 wrz 2000', 'Polska, Ghana', 'Prawy pomocnik', 19, '1,76m', 'prawa', 'Raków Częstochowa');
add_p('Jean Carlos', 'Silva', '10 maj 1996', 'Hiszpania, Brazylia', 'Lewy pomocnik', 20, '1,85m', 'prawa', 'Raków Częstochowa');
add_p('Erick', 'Otieno', '27 wrz 1996', 'Kenia', 'Lewy pomocnik', 26, '1,70m', 'lewa', 'Raków Częstochowa');
add_p('Adriano', 'Adriano', '15 lut 2002', 'Brazylia', 'Lewy pomocnik', 84, '1,75m', 'prawa', 'Raków Częstochowa');
add_p('Srdjan', 'Plavsic', '3 gru 1995', 'Serbia, Bośnia i Hercegowina', 'Lewy pomocnik', 14, '1,66m', 'lewa', 'Raków Częstochowa');
add_p('Ivi', 'López', '29 cze 1994', 'Hiszpania', 'Ofensywny pomocnik', 10, '1,74m', 'prawa', 'Raków Częstochowa');
add_p('Dawid', 'Drachal', '31 sty 2005', 'Polska', 'Ofensywny pomocnik', 81, '1,82m', 'obie', 'Raków Częstochowa');
add_p('Jesus', 'Díaz', '21 maj 1999', 'Kolumbia', 'Ofensywny pomocnik', 15, '1,83m', 'prawa', 'Raków Częstochowa');
add_p('Patryk', 'Makuch', '11 kwi 1999', 'Polska', 'Ofensywny pomocnik', 9, '1,87m', 'prawa', 'Raków Częstochowa');
add_p('Bartosz', 'Nowak', '25 sie 1993', 'Polska', 'Ofensywny pomocnik', 13, '1,80m', 'prawa', 'Raków Częstochowa');
add_p('Jakub', 'Myszor', '7 cze 2002', 'Polska', 'Ofensywny pomocnik', 52, '1,75m', 'obie', 'Raków Częstochowa');
add_p('Tobiasz', 'Mras', '10 cze 2007', 'Polska', 'Ofensywny pomocnik', 77, '1,76m', 'prawa', 'Raków Częstochowa');
add_p('Ibrahima', 'Seck', '19 maj 2004', 'Senegal', 'Ofensywny pomocnik', 97, '1,75m', 'prawa', 'Raków Częstochowa');
add_p('Kacper', 'Nowakowski', '19 cze 2006', 'Polska', 'Ofensywny pomocnik', 6, '1,77m', 'lewa', 'Raków Częstochowa');
add_p('Lazaros', 'Lamprou', '19 gru 1997', 'Grecja', 'Lewy napastnik', 27, '1,83m', 'prawa', 'Raków Częstochowa');
add_p('Ante', 'Crnac', '17 gru 2003', 'Chorwacja', 'Środkowy napastnik', 79, '1,90m', 'lewa', 'Raków Częstochowa');
add_p('Jonatan Braut', 'Brunes', '7 sie 2000', 'Norwegia', 'Środkowy napastnik', 18, '1,88m', 'lewa', 'Raków Częstochowa');
add_p('Leonardo', 'Rocha', '23 maj 1997', 'Portugalia, Brazylia', 'Środkowy napastnik', 17, '2,00m', 'prawa', 'Raków Częstochowa');
add_p('Adam', 'Basse', '4 lis 2007', 'Polska, Stany Zjednaczone', 'Środkowy napastnik', 99, '1,96m', 'prawa', 'Raków Częstochowa');
add_p('Tomasz', 'Walczak', '17 sie 2005', 'Polska', 'Środkowy napastnik', 29, '1,93m', 'obie', 'Raków Częstochowa');
add_p('David', 'Ezeh', '13 lut 2006', 'Finlandia, Nigeria', 'Środkowy napastnik', 95, '1,87m', 'prawa', 'Raków Częstochowa');
add_p('Kacper', 'Tobiasz', '4 lis 2002', 'Polska', 'Bramkarz', 1, '1,91m', 'lewa', 'Legia Warszawa');
add_p('Gabriel', 'Kobylak', '20 lut 2002', 'Polska', 'Bramkarz', 27, '1,90m', 'prawa', 'Legia Warszawa');
add_p('Marcel', 'Mendes-Dudziński', '14 maj 2005', 'Polska, Brazylia', 'Bramkarz', 31, '1,93m', 'prawa', 'Legia Warszawa');
add_p('Wojciech', 'Banasik', '8 maj 2006', 'Polska', 'Bramkarz', 93, '1,91m', 'prawa', 'Legia Warszawa');
add_p('Jakub', 'Zielinski', '21 lut 2008', 'Polska', 'Bramkarz', 72, '1,94m', 'prawa', 'Legia Warszawa');
add_p('Jan', 'Ziolkowski', '5 cze 2005', 'Polska', 'Środkowy obrońca', 24, '1,94m', 'prawa', 'Legia Warszawa');
add_p('Steve', 'Kapuadi', '30 kwi 1998', 'Demokratyczna Republika Kongo, Francja', 'Środkowy obrońca', 3, '1,96m', 'lewa', 'Legia Warszawa');
add_p('Radovan', 'Pankov', '5 sie 1995', 'Serbia', 'Środkowy obrońca', 12, '1,85m', 'prawa', 'Legia Warszawa');
add_p('Marco', 'Burch', '19 paź 2000', 'Szwajcaria', 'Środkowy obrońca', 17, '1,86m', 'prawa', 'Legia Warszawa');
add_p('Sergio', 'Barcia', '31 gru 2000', 'Hiszpania', 'Środkowy obrońca', 42, '1,86m', 'prawa', 'Legia Warszawa');
add_p('Jan', 'Leszczyński', '12 kwi 2007', 'Polska', 'Środkowy obrońca', 56, '1,91m', 'prawa', 'Legia Warszawa');
add_p('Artur', 'Jędrzejczyk', '4 lis 1987', 'Polska', 'Środkowy obrońca', 55, '1,89m', 'prawa', 'Legia Warszawa');
add_p('Rúben', 'Vinagre', '9 kwi 1999', 'Portugalia', 'Lewy obrońca', 19, '1,74m', 'lewa', 'Legia Warszawa');
add_p('Patryk', 'Kun', '20 kwi 1995', 'Polska', 'Lewy obrońca', 23, '1,65m', 'lewa', 'Legia Warszawa');
add_p('Paweł', 'Wszołek', '30 kwi 1992', 'Polska', 'Prawy obrońca', 13, '1,86m', 'prawa', 'Legia Warszawa');
add_p('Maxi', 'Oyedele', '7 lis 2004', 'Polska, Anglia', 'Defensywny pomocnik', 6, '1,83m', 'prawa', 'Legia Warszawa');
add_p('Jakub', 'Adkonis', '10 cze 2007', 'Polska', 'Defensywny pomocnik', 61, '1,82m', 'obie', 'Legia Warszawa');
add_p('Rafał', 'Augustyniak', '14 paź 1993', 'Polska', 'Defensywny pomocnik', 8, '1,85m', 'prawa', 'Legia Warszawa');
add_p('Claude', 'Gonçalves', '9 kwi 1994', 'Portugalia, Francja', 'Defensywny pomocnik', 5, '1,74m', 'prawa', 'Legia Warszawa');
add_p('Jurgen', 'Çelhaka', '6 gru 2000', 'Albania', 'Defensywny pomocnik', 73, '1,83m', 'prawa', 'Legia Warszawa');
add_p('Pascal', 'Mozie', '6 maj 2008', 'Polska, Nigeria', 'Defensywny pomocnik', 51, '1,86m', 'lewa', 'Legia Warszawa');
add_p('Aleksander', 'Wyganowski', '11 cze 2009', 'Polska', 'Defensywny pomocnik', 70, '1,77m', 'prawa', 'Legia Warszawa');
add_p('Oliwier', 'Olewiński', '15 lut 2006', 'Polska', 'Prawy pomocnik', 52, '1,73m', 'prawa', 'Legia Warszawa');
add_p('Ryoya', 'Morishita', '11 kwi 1997', 'Japonia', 'Ofensywny pomocnik', 25, '1,68m', 'prawa', 'Legia Warszawa');
add_p('Juergen', 'Elitim', '13 lip 1999', 'Kolumbia, Hiszpania', 'Ofensywny pomocnik', 22, '1,73m', 'lewa', 'Legia Warszawa');
add_p('Bartosz', 'Kapustka', '23 gru 1996', 'Polska', 'Ofensywny pomocnik', 67, '1,79m', 'prawa', 'Legia Warszawa');
add_p('Wojciech', 'Urbański', '12 sty 2005', 'Polska', 'Ofensywny pomocnik', 53, '1,84m', 'prawa', 'Legia Warszawa');
add_p('Mateusz', 'Szczepaniak', '5 sty 2007', 'Polska', 'Ofensywny pomocnik', 71, '1,79m', 'prawa', 'Legia Warszawa');
add_p('Igor', 'Strzałek', '19 sty 2004', 'Polska', 'Ofensywny pomocnik', 80, '1,83m', 'obie', 'Legia Warszawa');
add_p('Jakub', 'Żewłakow', '2 gru 2006', 'Polska', 'Ofensywny pomocnik', 20, '1,82m', 'prawa', 'Legia Warszawa');
add_p('Jakub', 'Jędrasik', '7 kwi 2005', 'Polska', 'Ofensywny pomocnik', 86, '1,79m', 'obie', 'Legia Warszawa');
add_p('Luquinhas', 'Luquinhas', '28 wrz 1996', 'Brazylia, Portugalia', 'Lewy napastnik', 82, '1,69m', 'prawa', 'Legia Warszawa');
add_p('Kacper', 'Chodyna', '24 maj 1999', 'Polska', 'Prawy napastnik', 11, '1,76m', 'prawa', 'Legia Warszawa');
add_p('Michal', 'Kucharczyk', '20 mar 1991', 'Polska', 'Prawy napastnik', 18, '1,78m', 'prawa', 'Legia Warszawa');
add_p('Marc', 'Gual', '13 mar 1996', 'Hiszpania', 'Środkowy napastnik', 28, '1,86m', 'prawa', 'Legia Warszawa');
add_p('Blaz', 'Kramer', '1 cze 1996', 'Słowenia', 'Środkowy napastnik', 43, '1,91m', 'prawa', 'Legia Warszawa');
add_p('Jean-Pierre', 'Nsame', '1 maj 1993', 'Kamerun, Francja', 'Środkowy napastnik', 62, '1,88m', 'prawa', 'Legia Warszawa');
add_p('Migouel', 'Alfarela', '15 lis 1997', 'Francja, Portugalia', 'Środkowy napastnik', 90, '1,73m', 'prawa', 'Legia Warszawa');
add_p('Jordan', 'Majchrzak', '8 paź 2004', 'Polska', 'Środkowy napastnik', 26, '1,92m', 'obie', 'Legia Warszawa');
add_p('Tomas', 'Pekhart', '26 maj 1989', 'Czechy', 'Środkowy napastnik', 7, '1,94m', 'prawa', 'Legia Warszawa');
add_p('Sławomir', 'Abramowicz', '9 cze 2004', 'Polska', 'Bramkarz', 50, '1,89m', 'lewa', 'Jagiellonia Białystok');
add_p('Miłosz', 'Piekutowski', '8 maj 2006', 'Polska', 'Bramkarz', 32, '1,90m', 'obie', 'Jagiellonia Białystok');
add_p('Maksymilian', 'Stryjek', '18 lip 1996', 'Polska, Anglia', 'Bramkarz', 1, '1,88m', 'prawa', 'Jagiellonia Białystok');
add_p('Bartłomiej', 'Zynel', '9 kwi 1998', 'Polska', 'Bramkarz', 33, '1,87m', 'lewa', 'Jagiellonia Białystok');
add_p('Jakub', 'Suchocki', '7 cze 2006', 'Polska', 'Bramkarz', 89, '1,88m', 'prawa', 'Jagiellonia Białystok');
add_p('Mateusz', 'Skrzypczak', '22 sie 2000', 'Polska', 'Środkowy obrońca', 72, '1,91m', 'prawa', 'Jagiellonia Białystok');
add_p('Enzo', 'Ebosse', '11 mar 1999', 'Kamerun, Francja', 'Środkowy obrońca', 23, '1,85m', 'lewa', 'Jagiellonia Białystok');
add_p('Adrian', 'Diéguez', '4 lut 1996', 'Hiszpania', 'Środkowy obrońca', 17, '1,88m', 'lewa', 'Jagiellonia Białystok');
add_p('Dusan', 'Stojinovic', '26 sie 2000', 'Słowenia', 'Środkowy obrońca', 3, '1,87m', 'prawa', 'Jagiellonia Białystok');
add_p('Jetmir', 'Haliti', '14 wrz 1996', 'Kosowo, Szwecja', 'Środkowy obrońca', 35, '1,88m', 'prawa', 'Jagiellonia Białystok');
add_p('Dimitrios', 'Retsos', '7 sie 2004', 'Grecja', 'Środkowy obrońca', 87, '1,88m', 'lewa', 'Jagiellonia Białystok');
add_p('João', 'Moutinho', '12 sty 1998', 'Portugalia', 'Lewy obrońca', 44, '1,83m', 'lewa', 'Jagiellonia Białystok');
add_p('Cezary', 'Polak', '31 maj 2003', 'Polska', 'Lewy obrońca', 5, '1,85m', 'lewa', 'Jagiellonia Białystok');
add_p('Jakub', 'Lewicki', '17 wrz 2005', 'Polska', 'Lewy obrońca', 92, '1,82m', 'obie', 'Jagiellonia Białystok');
add_p('Michał', 'Sacek', '19 wrz 1996', 'Czechy', 'Prawy obrońca', 16, '1,80m', 'prawa', 'Jagiellonia Białystok');
add_p('Peter', 'Kovacik', '1 gru 2001', 'Słowacja', 'Prawy obrońca', 94, '1,77m', 'prawa', 'Jagiellonia Białystok');
add_p('Norbert', 'Wojtuszek', '5 paź 2001', 'Polska', 'Prawy obrońca', 15, '1,84m', 'prawa', 'Jagiellonia Białystok');
add_p('Paweł', 'Olszewski', '7 cze 1999', 'Polska', 'Prawy obrońca', 29, '1,78m', 'prawa', 'Jagiellonia Białystok');
add_p('Leon', 'Flach', '28 lut 2001', 'Stany Zjednaczone, Niemcy', 'Defensywny pomocnik', 31, '1,83m', 'lewa', 'Jagiellonia Białystok');
add_p('Nené', 'Nené', '10 cze 1995', 'Portugalia', 'Defensywny pomocnik', 76, '1,87m', 'lewa', 'Jagiellonia Białystok');
add_p('Jarosław', 'Kubicki', '7 sie 1995', 'Polska', 'Defensywny pomocnik', 14, '1,80m', 'prawa', 'Jagiellonia Białystok');
add_p('Aurélien', 'Nguiamba', '18 sty 1999', 'Francja, Kamerun', 'Defensywny pomocnik', 36, '1,79m', 'lewa', 'Jagiellonia Białystok');
add_p('Taras', 'Romanczuk', '14 lis 1991', 'Polska', 'Defensywny pomocnik', 6, '1,86m', 'lewa', 'Jagiellonia Białystok');
add_p('Szymon', 'Stypułkowski', '17 mar 2006', 'Polska', 'Defensywny pomocnik', 71, '1,82m', 'prawa', 'Jagiellonia Białystok');
add_p('Eryk', 'Kozłowski', '27 wrz 2006', 'Polska', 'Defensywny pomocnik', 85, '1,81m', 'lewa', 'Jagiellonia Białystok');
add_p('Lamine', 'Diaby-Fadiga', '19 sty 2001', 'Gwinea, Francja', 'Ofensywny pomocnik', 9, '1,88m', 'lewa', 'Jagiellonia Białystok');
add_p('Jesus', 'Imaz', '26 wrz 1990', 'Hiszpania', 'Ofensywny pomocnik', 11, '1,74m', 'prawa', 'Jagiellonia Białystok');
add_p('Marcin', 'Listkowski', '10 lut 1998', 'Polska', 'Ofensywny pomocnik', 95, '1,78m', 'obie', 'Jagiellonia Białystok');
add_p('Wojciech', 'Łaski', '21 maj 2000', 'Polska', 'Ofensywny pomocnik', 37, '1,86m', 'prawa', 'Jagiellonia Białystok');
add_p('Bartosz', 'Mazurek', '3 sty 2007', 'Polska', 'Ofensywny pomocnik', 86, '1,80m', 'prawa', 'Jagiellonia Białystok');
add_p('Oskar', 'Pietuszewski', '20 maj 2008', 'Polska', 'Lewy napastnik', 80, '1,79m', 'prawa', 'Jagiellonia Białystok');
add_p('Darko', 'Churlinov', '11 lip 2000', 'Macedonia Północna', 'Lewy napastnik', 21, '1,80m', 'prawa', 'Jagiellonia Białystok');
add_p('Kristoffer', 'Hansen', '12 sie 1994', 'Norwegia', 'Lewy napastnik', 99, '1,80m', 'prawa', 'Jagiellonia Białystok');
add_p('Tomas', 'Silva', '15 paź 1999', 'Portugalia', 'Lewy napastnik', 82, '1,72m', 'prawa', 'Jagiellonia Białystok');
add_p('Dominik', 'Marczuk', '1 lis 2003', 'Polska', 'Prawy napastnik', 61, '1,77m', 'obie', 'Jagiellonia Białystok');
add_p('Miki', 'Villar', '19 wrz 1996', 'Hiszpania', 'Prawy napastnik', 20, '1,73m', 'prawa', 'Jagiellonia Białystok');
add_p('Edi', 'Semedo', '1 cze 1999', 'Republika Zielonego Przylądka, Portugalia', 'Prawy napastnik', 7, '1,81m', 'prawa', 'Jagiellonia Białystok');
add_p('Afimico', 'Pululu', '23 mar 1999', 'Demokratyczna Republika Kongo, Francja', 'Środkowy napastnik', 10, '1,75m', 'lewa', 'Jagiellonia Białystok');
add_p('Alan', 'Rybak', '1 gru 2006', 'Polska', '', 51, '1,85m', 'obie', 'Jagiellonia Białystok');
add_p('Henrich', 'Ravas', '16 sie 1997', 'Słowacja', 'Bramkarz', 27, '1,95m', 'prawa', 'Cracovia');
add_p('Sebastian', 'Madejski', '2 sty 1997', 'Polska', 'Bramkarz', 13, '1,89m', 'prawa', 'Cracovia');
add_p('Jakub', 'Burek', '8 mar 2003', 'Polska', 'Bramkarz', 26, '1,88m', 'obie', 'Cracovia');
add_p('Konrad', 'Golonka', '26 maj 2007', 'Polska', 'Bramkarz', 43, '1,88m', 'prawa', 'Cracovia');
add_p('Virgil', 'Ghiță', '4 cze 1998', 'Rumunia', 'Środkowy obrońca', 5, '1,86m', 'prawa', 'Cracovia');
add_p('Gustav', 'Henriksson', '3 lut 1998', 'Szwecja', 'Środkowy obrońca', 4, '1,90m', 'prawa', 'Cracovia');
add_p('Andreas', 'Skovgaard', '27 mar 1997', 'Dania', 'Środkowy obrońca', 3, '1,85m', 'lewa', 'Cracovia');
add_p('Arttu', 'Hoskonen', '16 kwi 1997', 'Finlandia', 'Środkowy obrońca', 22, '1,88m', 'prawa', 'Cracovia');
add_p('Jakub', 'Jugas', '5 maj 1992', 'Czechy', 'Środkowy obrońca', 24, '1,88m', 'prawa', 'Cracovia');
add_p('Kamil', 'Glik', '3 lut 1988', 'Polska, Niemcy', 'Środkowy obrońca', 15, '1,90m', 'prawa', 'Cracovia');
add_p('Oskar', 'Wójcik', '21 lip 2003', 'Polska', 'Środkowy obrońca', 66, '1,91m', 'prawa', 'Cracovia');
add_p('Kuba', 'Pestka', '2 wrz 2005', 'Polska', 'Środkowy obrońca', 33, '1,90m', 'prawa', 'Cracovia');
add_p('Patryk', 'Janasik', '25 sie 1997', 'Polska', 'Lewy obrońca', 77, '1,78m', 'prawa', 'Cracovia');
add_p('Paweł', 'Jaroszyński', '2 paź 1994', 'Polska', 'Lewy obrońca', 59, '1,84m', 'lewa', 'Cracovia');
add_p('Mikkel', 'Maigaard', '20 wrz 1995', 'Dania', 'Defensywny pomocnik', 11, '1,80m', 'prawa', 'Cracovia');
add_p('Amir', 'Al-Ammari', '27 lip 1997', 'Irak, Szwecja', 'Defensywny pomocnik', 6, '1,84m', 'lewa', 'Cracovia');
add_p('Jani', 'Atanasov', '31 paź 1999', 'Macedonia Północna, Bułgaria', 'Defensywny pomocnik', 30, '1,87m', 'prawa', 'Cracovia');
add_p('Patryk', 'Sokołowski', '25 wrz 1994', 'Polska', 'Defensywny pomocnik', 88, '1,82m', 'prawa', 'Cracovia');
add_p('Karol', 'Knap', '12 wrz 2001', 'Polska', 'Defensywny pomocnik', 91, '1,80m', 'lewa', 'Cracovia');
add_p('Dawid', 'Polak', '28 cze 2008', 'Polska', 'Defensywny pomocnik', 28, '-', 'prawa', 'Cracovia');
add_p('Mateusz', 'Pomietlo', '6 lip 2007', 'Polska', 'Defensywny pomocnik', 86, '1,81m', 'prawa', 'Cracovia');
add_p('Otar', 'Kakabadze', '27 cze 1995', 'Gruzja', 'Prawy pomocnik', 25, '1,86m', 'prawa', 'Cracovia');
add_p('Mateusz', 'Bochnak', '11 lut 1998', 'Polska', 'Prawy pomocnik', 67, '1,79m', 'prawa', 'Cracovia');
add_p('Mauro', 'Perkovic', '22 mar 2003', 'Chorwacja', 'Lewy pomocnik', 39, '1,85m', 'lewa', 'Cracovia');
add_p('Davíd', 'Kristján Olafsson', '15 maj 1995', 'Islandia', 'Lewy pomocnik', 19, '1,84m', 'lewa', 'Cracovia');
add_p('Bartosz', 'Biedrzycki', '16 kwi 2003', 'Polska', 'Lewy pomocnik', 16, '1,80m', 'lewa', 'Cracovia');
add_p('Filip', 'Rózga', '7 sie 2006', 'Polska', 'Ofensywny pomocnik', 18, '1,76m', 'lewa', 'Cracovia');
add_p('Ajdin', 'Hasic', '7 paź 2001', 'Bośnia i Hercegowina', 'Ofensywny pomocnik', 14, '1,80m', 'lewa', 'Cracovia');
add_p('Martin', 'Minchev', '22 kwi 2001', 'Bułgaria', 'Ofensywny pomocnik', 10, '1,85m', 'prawa', 'Cracovia');
add_p('Michał', 'Rakoczy', '30 mar 2002', 'Polska', 'Ofensywny pomocnik', 52, '1,77m', 'obie', 'Cracovia');
add_p('Fabian', 'Bzdyl', '2 gru 2007', 'Polska', 'Ofensywny pomocnik', 23, '1,80m', 'prawa', 'Cracovia');
add_p('Oskar', 'Lachowicz', '19 kwi 2005', 'Polska', 'Ofensywny pomocnik', 72, '1,80m', 'prawa', 'Cracovia');
add_p('Benjamin', 'Kallman', '17 cze 1998', 'Finlandia', 'Środkowy napastnik', 9, '1,82m', 'prawa', 'Cracovia');
add_p('Mick', 'van Buren', '24 sie 1992', 'Holandia', 'Środkowy napastnik', 7, '1,84m', 'prawa', 'Cracovia');
add_p('Kacper', 'Śmiglewski', '7 sty 2005', 'Polska', '', 21, '1,90m', 'prawa', 'Cracovia');
add_p('Valentin', 'Cojocaru', '1 paź 1995', 'Rumunia', 'Bramkarz', 77, '1,95m', 'prawa', 'Pogoń Szczecin');
add_p('Krzysztof', 'Kamiński', '26 lis 1990', 'Polska', 'Bramkarz', 31, '1,91m', 'prawa', 'Pogoń Szczecin');
add_p('Lukasz', 'Legowski', '29 sty 2003', 'Polska', 'Bramkarz', 66, '1,82m', 'prawa', 'Pogoń Szczecin');
add_p('Kuba', 'Bochniarz', '5 mar 2009', 'Polska', 'Bramkarz', 91, '1,87m', 'prawa', 'Pogoń Szczecin');
add_p('Léo', 'Borges', '3 sty 2001', 'Brazylia', 'Środkowy obrońca', 4, '1,79m', 'lewa', 'Pogoń Szczecin');
add_p('Danijel', 'Loncar', '26 cze 1997', 'Chorwacja, Bośnia i Hercegowina', 'Środkowy obrońca', 68, '1,87m', 'prawa', 'Pogoń Szczecin');
add_p('Luizão', 'Luizão', '8 mar 2002', 'Brazylia', 'Środkowy obrońca', 6, '1,87m', 'lewa', 'Pogoń Szczecin');
add_p('Mariusz', 'Malec', '4 kwi 1995', 'Polska', 'Środkowy obrońca', 33, '1,91m', 'lewa', 'Pogoń Szczecin');
add_p('Dimitrios', 'Keramitsis', '1 lip 2004', 'Grecja', 'Środkowy obrońca', 13, '1,93m', 'obie', 'Pogoń Szczecin');
add_p('Benedikt', 'Zech', '3 lis 1990', 'Austria', 'Środkowy obrońca', 78, '1,86m', 'prawa', 'Pogoń Szczecin');
add_p('Wojciech', 'Lisowski', '10 lut 1992', 'Polska', 'Środkowy obrońca', 25, '1,86m', 'prawa', 'Pogoń Szczecin');
add_p('Leonardo', 'Koutris', '23 lip 1995', 'Grecja, Brazylia', 'Lewy obrońca', 32, '1,70m', 'lewa', 'Pogoń Szczecin');
add_p('Jakub', 'Zawadzki', '22 wrz 2008', 'Polska', 'Lewy obrońca', 36, '1,70m', 'prawa', 'Pogoń Szczecin');
add_p('Linus', 'Wahlqvist', '11 lis 1996', 'Szwecja', 'Prawy obrońca', 28, '1,85m', 'prawa', 'Pogoń Szczecin');
add_p('Benjamín', 'Rojas', '1 mar 2001', 'Chile', 'Prawy obrońca', 3, '1,79m', 'prawa', 'Pogoń Szczecin');
add_p('Jakub', 'Lis', '14 sty 2002', 'Polska', 'Prawy obrońca', 17, '1,75m', 'prawa', 'Pogoń Szczecin');
add_p('João', 'Gamboa', '31 sie 1996', 'Portugalia', 'Defensywny pomocnik', 21, '1,87m', 'prawa', 'Pogoń Szczecin');
add_p('Kacper', 'Łukasiak', '24 wrz 2003', 'Polska', 'Defensywny pomocnik', 19, '1,80m', 'prawa', 'Pogoń Szczecin');
add_p('Fredrik', 'Ulvestad', '17 cze 1992', 'Norwegia', 'Defensywny pomocnik', 8, '1,83m', 'prawa', 'Pogoń Szczecin');
add_p('Stanislaw', 'Wawrzynowicz', '13 mar 1999', 'Polska', 'Defensywny pomocnik', 18, '1,77m', 'obie', 'Pogoń Szczecin');
add_p('Adrian', 'Przyborek', '1 sty 2007', 'Polska', 'Ofensywny pomocnik', 10, '1,84m', 'prawa', 'Pogoń Szczecin');
add_p('Marcel', 'Wędrychowski', '13 sty 2002', 'Polska', 'Ofensywny pomocnik', 15, '1,73m', 'obie', 'Pogoń Szczecin');
add_p('Rafał', 'Kurzawa', '29 sty 1993', 'Polska', 'Ofensywny pomocnik', 7, '1,82m', 'lewa', 'Pogoń Szczecin');
add_p('Kacper', 'Smoliński', '7 lut 2001', 'Polska', 'Ofensywny pomocnik', 61, '1,78m', 'lewa', 'Pogoń Szczecin');
add_p('Alexander', 'Gorgon', '28 paź 1988', 'Austria', 'Ofensywny pomocnik', 75, '1,85m', 'prawa', 'Pogoń Szczecin');
add_p('Maciej', 'Wojciechowski', '17 maj 2007', 'Polska', 'Ofensywny pomocnik', 35, '1,78m', 'prawa', 'Pogoń Szczecin');
add_p('Kamil', 'Grosicki', '8 cze 1988', 'Polska', 'Lewy napastnik', 11, '1,80m', 'prawa', 'Pogoń Szczecin');
add_p('Olaf', 'Korczakowski', '11 lis 2003', 'Polska', 'Lewy napastnik', 27, '1,83m', 'prawa', 'Pogoń Szczecin');
add_p('Mateusz', 'Bak', '1 lip 2003', 'Polska', 'Lewy napastnik', 60, '1,81m', 'prawa', 'Pogoń Szczecin');
add_p('Vahan', 'Bichakhchyan', '9 lip 1999', 'Armenia', 'Prawy napastnik', 80, '1,72m', 'lewa', 'Pogoń Szczecin');
add_p('Renyer', 'Renyer', '12 lip 2003', 'Brazylia', 'Prawy napastnik', 55, '1,74m', 'lewa', 'Pogoń Szczecin');
add_p('Antoni', 'Klukowski', '2 kwi 2007', 'Kanada, Polska', 'Prawy napastnik', 46, '1,86m', 'lewa', 'Pogoń Szczecin');
add_p('Efthymios', 'Koulouris', '6 mar 1996', 'Grecja', 'Środkowy napastnik', 9, '1,86m', 'prawa', 'Pogoń Szczecin');
add_p('Patryk', 'Paryzek', '3 lut 2006', 'Polska', '', 51, '1,92m', 'prawa', 'Pogoń Szczecin');
add_p('Michał', 'Szromnik', '4 mar 1993', 'Polska', 'Bramkarz', 25, '1,90m', 'prawa', 'Górnik Zabrze');
add_p('Filip', 'Majchrowicz', '9 lut 2000', 'Polska', 'Bramkarz', 1, '1,94m', 'prawa', 'Górnik Zabrze');
add_p('Mateusz', 'Jeleń', '2 lut 2007', 'Polska', 'Bramkarz', 31, '1,95m', 'prawa', 'Górnik Zabrze');
add_p('Filip', 'Prebsl', '4 mar 2003', 'Czechy', 'Środkowy obrońca', 38, '1,88m', 'prawa', 'Górnik Zabrze');
add_p('Dominik', 'Szala', '24 kwi 2006', 'Polska', 'Środkowy obrońca', 27, '1,88m', 'prawa', 'Górnik Zabrze');
add_p('Josema', 'Josema', '6 cze 1996', 'Hiszpania', 'Środkowy obrońca', 20, '1,82m', 'lewa', 'Górnik Zabrze');
add_p('Rafał', 'Janicki', '5 lip 1992', 'Polska', 'Środkowy obrońca', 26, '1,88m', 'prawa', 'Górnik Zabrze');
add_p('Radosław', 'Szafrański', '17 lut 2006', 'Polska', 'Środkowy obrońca', 24, '-', 'obie', 'Górnik Zabrze');
add_p('Erik', 'Janza', '21 cze 1993', 'Słowenia', 'Lewy obrońca', 64, '1,75m', 'lewa', 'Górnik Zabrze');
add_p('Dawid', 'Mazurek', '30 mar 2007', 'Polska', 'Lewy obrońca', 41, '1,72m', 'lewa', 'Górnik Zabrze');
add_p('Matúš', 'Kmeť', '27 cze 2000', 'Słowacja', 'Prawy obrońca', 81, '1,73m', 'prawa', 'Górnik Zabrze');
add_p('Kryspin', 'Szcześniak', '8 sty 2001', 'Polska', 'Prawy obrońca', 5, '1,86m', 'prawa', 'Górnik Zabrze');
add_p('Paweł', 'Olkowski', '13 lut 1990', 'Polska', 'Prawy obrońca', 16, '1,84m', 'prawa', 'Górnik Zabrze');
add_p('Patrik', 'Hellebrand', '16 maj 1999', 'Czechy', 'Ofensywny pomocnik', 8, '1,80m', 'prawa', 'Górnik Zabrze');
add_p('Lukas', 'Ambros', '5 cze 2004', 'Czechy', 'Ofensywny pomocnik', 18, '1,82m', 'lewa', 'Górnik Zabrze');
add_p('Matija', 'Marsenić', '3 sty 2005', 'Czarnogóra', 'Ofensywny pomocnik', 80, '1,79m', 'obie', 'Górnik Zabrze');
add_p('Yosuke', 'Furukawa', '16 lip 2003', 'Japonia', 'Lewy napastnik', 88, '1,74m', 'prawa', 'Górnik Zabrze');
add_p('Kamil', 'Lukoszek', '4 kwi 2002', 'Polska', 'Lewy napastnik', 17, '1,75m', 'lewa', 'Górnik Zabrze');
add_p('Abbati', 'Abdullahi', '3 sty 2006', 'Nigeria', 'Lewy napastnik', 22, '1,78m', 'prawa', 'Górnik Zabrze');
add_p('Taofeek', 'Ismaheel', '16 lip 2000', 'Nigeria', 'Prawy napastnik', 11, '1,72m', 'prawa', 'Górnik Zabrze');
add_p('Ousmane', 'Sow', '5 lip 2000', 'Francja, Senegal', 'Prawy napastnik', 30, '1,85m', 'lewa', 'Górnik Zabrze');
add_p('Aleksander', 'Tobolik', '13 mar 2006', 'Polska', 'Prawy napastnik', 14, '1,74m', 'prawa', 'Górnik Zabrze');
add_p('Luka', 'Zahović', '15 lis 1995', 'Słowenia, Portugalia', 'Środkowy napastnik', 7, '1,77m', 'prawa', 'Górnik Zabrze');
add_p('Sinan', 'Bakış', '22 kwi 1994', 'Turcja, Niemcy', 'Środkowy napastnik', 9, '1,88m', 'prawa', 'Górnik Zabrze');
add_p('Sondre', 'Liseth', '30 wrz 1997', 'Norwegia', 'Środkowy napastnik', 23, '1,85m', 'prawa', 'Górnik Zabrze');
add_p('Aleksander', 'Buksa', '15 sty 2003', 'Polska', 'Środkowy napastnik', 44, '1,89m', 'lewa', 'Górnik Zabrze');
add_p('Lukas', 'Podolski', '4 cze 1985', 'Niemcy, Polska', 'Środkowy napastnik', 10, '1,82m', 'lewa', 'Górnik Zabrze');
add_p('Dominik', 'Hładun', '17 wrz 1995', 'Polska', 'Bramkarz', 30, '1,90m', 'lewa', 'Zagłębie Lubin');
add_p('Jasmin', 'Burić', '18 lut 1987', 'Bośnia i Hercegowina, Polska', 'Bramkarz', 1, '1,93m', 'prawa', 'Zagłębie Lubin');
add_p('Michał', 'Matys', '6 maj 2006', 'Polska', 'Bramkarz', 34, '1,89m', 'prawa', 'Zagłębie Lubin');
add_p('Aleks', 'Ławniczak', '5 maj 1999', 'Polska', 'Środkowy obrońca', 5, '1,89m', 'prawa', 'Zagłębie Lubin');
add_p('Damian', 'Michalski', '17 maj 1998', 'Polska', 'Środkowy obrońca', 4, '1,89m', 'prawa', 'Zagłębie Lubin');
add_p('Michał', 'Nalepa', '22 sty 1993', 'Polska', 'Środkowy obrońca', 25, '1,90m', 'prawa', 'Zagłębie Lubin');
add_p('Jaroslaw', 'Jach', '17 lut 1994', 'Polska', 'Środkowy obrońca', 33, '1,92m', 'lewa', 'Zagłębie Lubin');
add_p('Tomasz', 'Makowski', '19 lip 1999', 'Polska', 'Defensywny pomocnik', 6, '1,83m', 'prawa', 'Zagłębie Lubin');
add_p('Damian', 'Dąbrowski', '27 sie 1992', 'Polska', 'Defensywny pomocnik', 8, '1,78m', 'prawa', 'Zagłębie Lubin');
add_p('Igor', 'Orlikowski', '9 lut 2006', 'Polska', 'Prawy pomocnik', 31, '1,81m', 'prawa', 'Zagłębie Lubin');
add_p('Josip', 'Corluka', '3 mar 1995', 'Bośnia i Hercegowina, Chorwacja', 'Prawy pomocnik', 16, '1,84m', 'prawa', 'Zagłębie Lubin');
add_p('Mateusz', 'Grzybek', '30 mar 1996', 'Polska', 'Prawy pomocnik', 13, '1,78m', 'prawa', 'Zagłębie Lubin');
add_p('Tomasz', 'Pieńko', '5 sty 2004', 'Polska', 'Ofensywny pomocnik', 21, '1,85m', 'prawa', 'Zagłębie Lubin');
add_p('Kajetan', 'Szmyt', '29 maj 2002', 'Polska', 'Ofensywny pomocnik', 77, '1,71m', 'prawa', 'Zagłębie Lubin');
add_p('Mateusz', 'Wdowiak', '28 sie 1996', 'Polska', 'Ofensywny pomocnik', 17, '1,74m', 'prawa', 'Zagłębie Lubin');
add_p('Dawid', 'Kurminowski', '24 lut 1999', 'Polska', 'Środkowy napastnik', 90, '1,82m', 'prawa', 'Zagłębie Lubin');
add_p('Jan', 'Kowalski', '26 sty 2006', 'Polska', 'Pomocnik', 24, '1,80m', 'prawa', 'Zagłębie Lubin');
add_p('Mateusz', 'Kowalczyk', '4 lis 2006', 'Polska', 'Pomocnik', 91, '1,80m', 'prawa', 'Zagłębie Lubin');
add_p('Łukasz', 'Kamiński', '9 lis 2005', 'Polska', 'Pomocnik', 84, '1,80m', 'prawa', 'Zagłębie Lubin');
add_p('Tomasz', 'Krawczyk', '2 sie 2006', 'Polska', 'Pomocnik', 75, '1,80m', 'prawa', 'Zagłębie Lubin');
add_p('Mikołaj', 'Jankowski', '27 mar 2004', 'Polska', 'Pomocnik', 27, '1,80m', 'prawa', 'Zagłębie Lubin');
add_p('Jan', 'Kowalski', '16 paź 2007', 'Polska', 'Pomocnik', 54, '1,80m', 'prawa', 'Zagłębie Lubin');
add_p('Tomasz', 'Krawczyk', '12 sty 2003', 'Polska', 'Pomocnik', 37, '1,80m', 'prawa', 'Zagłębie Lubin');
add_p('Szymon', 'Kozłowski', '1 lis 2007', 'Polska', 'Pomocnik', 86, '1,80m', 'prawa', 'Zagłębie Lubin');
add_p('Tomasz', 'Krawczyk', '16 sty 2004', 'Polska', 'Pomocnik', 10, '1,80m', 'prawa', 'Zagłębie Lubin');
add_p('Tomasz', 'Loska', '26 sty 1996', 'Polska', 'Bramkarz', 1, '1,90m', 'prawa', 'Śląsk Wrocław');
add_p('Rafał', 'Leszczyński', '26 kwi 1992', 'Polska', 'Bramkarz', 12, '1,87m', 'prawa', 'Śląsk Wrocław');
add_p('Alex', 'Petkov', '25 lip 1999', 'Bułgaria', 'Środkowy obrońca', 5, '1,93m', 'prawa', 'Śląsk Wrocław');
add_p('Yegor', 'Matsenko', '23 sty 2002', 'Ukraina', 'Lewy obrońca', 33, '1,88m', 'obie', 'Śląsk Wrocław');
add_p('Marc', 'Llinares', '26 sie 1999', 'Hiszpania', 'Lewy obrońca', 28, '1,79m', 'lewa', 'Śląsk Wrocław');
add_p('Peter', 'Pokorný', '8 sie 2001', 'Słowacja', 'Defensywny pomocnik', 16, '1,83m', 'prawa', 'Śląsk Wrocław');
add_p('Tudor', 'Băluță', '27 mar 1999', 'Rumunia', 'Defensywny pomocnik', 21, '1,92m', 'prawa', 'Śląsk Wrocław');
add_p('Petr', 'Schwarz', '12 lis 1991', 'Czechy', 'Defensywny pomocnik', 17, '1,74m', 'prawa', 'Śląsk Wrocław');
add_p('Jose', 'Pozo', '15 mar 1996', 'Hiszpania', 'Ofensywny pomocnik', 8, '1,71m', 'lewa', 'Śląsk Wrocław');
add_p('Marcin', 'Cebula', '6 gru 1995', 'Polska', 'Ofensywny pomocnik', 77, '1,77m', 'obie', 'Śląsk Wrocław');
add_p('Mateusz', 'Żukowski', '23 lis 2001', 'Polska', 'Lewy napastnik', 22, '1,85m', 'prawa', 'Śląsk Wrocław');
add_p('Piotr', 'Samiec-Talar', '2 lis 2001', 'Polska', 'Prawy napastnik', 7, '1,81m', 'lewa', 'Śląsk Wrocław');
add_p('Jakub', 'Świerczok', '28 gru 1992', 'Polska', 'Środkowy napastnik', 10, '1,84m', 'prawa', 'Śląsk Wrocław');
add_p('Sebastian', 'Musiolik', '19 maj 1996', 'Polska', 'Środkowy napastnik', 11, '1,93m', 'lewa', 'Śląsk Wrocław');
add_p('Filip', 'Dąbrowski', '21 paź 2005', 'Polska', 'Pomocnik', 76, '1,80m', 'prawa', 'Śląsk Wrocław');
add_p('Krzysztof', 'Wiśniewski', '9 lut 2006', 'Polska', 'Pomocnik', 6, '1,80m', 'prawa', 'Śląsk Wrocław');
add_p('Mateusz', 'Kowalczyk', '26 gru 2005', 'Polska', 'Pomocnik', 45, '1,80m', 'prawa', 'Śląsk Wrocław');
add_p('Jan', 'Kowalski', '1 paź 2007', 'Polska', 'Pomocnik', 58, '1,80m', 'prawa', 'Śląsk Wrocław');
add_p('Jakub', 'Szymański', '18 lis 2004', 'Polska', 'Pomocnik', 64, '1,80m', 'prawa', 'Śląsk Wrocław');
add_p('Jakub', 'Szymański', '17 mar 2006', 'Polska', 'Pomocnik', 99, '1,80m', 'prawa', 'Śląsk Wrocław');
add_p('Mikołaj', 'Jankowski', '10 paź 2007', 'Polska', 'Pomocnik', 27, '1,80m', 'prawa', 'Śląsk Wrocław');
add_p('Szymon', 'Kozłowski', '28 sie 2006', 'Polska', 'Pomocnik', 93, '1,80m', 'prawa', 'Śląsk Wrocław');
add_p('Filip', 'Dąbrowski', '16 gru 2004', 'Polska', 'Pomocnik', 36, '1,80m', 'prawa', 'Śląsk Wrocław');
add_p('Jakub', 'Szymański', '13 sty 2006', 'Polska', 'Pomocnik', 83, '1,80m', 'prawa', 'Śląsk Wrocław');
add_p('Jan', 'Kowalski', '2 lut 2004', 'Polska', 'Pomocnik', 42, '1,80m', 'prawa', 'Śląsk Wrocław');
add_p('Frantisek', 'Plach', '8 mar 1992', 'Słowacja', 'Bramkarz', 26, '1,92m', 'lewa', 'Piast Gliwice');
add_p('Karol', 'Szymański', '25 cze 1993', 'Polska', 'Bramkarz', 33, '1,92m', 'prawa', 'Piast Gliwice');
add_p('Bartlomiej', 'Jelonek', '22 gru 2001', 'Polska', 'Bramkarz', 12, '1,88m', 'prawa', 'Piast Gliwice');
add_p('Dawid', 'Rychta', '4 mar 2006', 'Polska', 'Bramkarz', 79, '1,92m', 'prawa', 'Piast Gliwice');
add_p('Ariel', 'Mosór', '19 lut 2003', 'Polska', 'Środkowy obrońca', 76, '1,84m', 'prawa', 'Piast Gliwice');
add_p('Igor', 'Drapiński', '31 maj 2004', 'Polska', 'Środkowy obrońca', 29, '1,86m', 'lewa', 'Piast Gliwice');
add_p('Tomas', 'Huk', '22 gru 1994', 'Słowacja', 'Środkowy obrońca', 5, '1,84m', 'prawa', 'Piast Gliwice');
add_p('Miguel', 'Nóbrega', '17 kwi 2000', 'Portugalia', 'Środkowy obrońca', 14, '1,90m', 'prawa', 'Piast Gliwice');
add_p('Miguel', 'Muñoz', '22 lis 1996', 'Hiszpania', 'Środkowy obrońca', 3, '1,85m', 'prawa', 'Piast Gliwice');
add_p('Jakub', 'Czerwiński', '6 sie 1991', 'Polska', 'Środkowy obrońca', 4, '1,83m', 'obie', 'Piast Gliwice');
add_p('Levis', 'Pitan', '24 maj 2005', 'Polska, Anglia', 'Środkowy obrońca', 15, '1,93m', 'prawa', 'Piast Gliwice');
add_p('Jakub', 'Lewicki', '17 wrz 2005', 'Polska', 'Lewy obrońca', 36, '1,82m', 'obie', 'Piast Gliwice');
add_p('Arkadiusz', 'Pyrka', '20 wrz 2002', 'Polska', 'Prawy obrońca', 77, '1,77m', 'prawa', 'Piast Gliwice');
add_p('Akim', 'Zedadka', '30 maj 1995', 'Algieria, Francja', 'Prawy obrońca', 2, '1,74m', 'prawa', 'Piast Gliwice');
add_p('Tomasz', 'Mokwa', '10 lut 1993', 'Polska', 'Prawy obrońca', 22, '1,81m', 'prawa', 'Piast Gliwice');
add_p('Patryk', 'Dziczek', '25 mar 1998', 'Polska', 'Defensywny pomocnik', 10, '1,82m', 'prawa', 'Piast Gliwice');
add_p('Grzegorz', 'Tomasiewicz', '5 maj 1996', 'Polska', 'Defensywny pomocnik', 20, '1,69m', 'obie', 'Piast Gliwice');
add_p('Tihomir', 'Kostadinov', '4 mar 1996', 'Macedonia Północna', 'Defensywny pomocnik', 96, '1,79m', 'prawa', 'Piast Gliwice');
add_p('Oskar', 'Leśniak', '7 paź 2004', 'Polska', 'Defensywny pomocnik', 31, '1,76m', 'prawa', 'Piast Gliwice');
add_p('Mateusz', 'Kopczyński', '17 gru 2007', 'Polska', 'Defensywny pomocnik', 16, '1,86m', 'prawa', 'Piast Gliwice');
add_p('Justin', 'Daniel', '14 lut 2005', 'Polska', 'Defensywny pomocnik', 27, '1,81m', 'prawa', 'Piast Gliwice');
add_p('Miłosz', 'Szczepański', '22 mar 1998', 'Polska', 'Ofensywny pomocnik', 30, '1,68m', 'prawa', 'Piast Gliwice');
add_p('Michał', 'Chrapek', '3 kwi 1992', 'Polska', 'Ofensywny pomocnik', 6, '1,75m', 'prawa', 'Piast Gliwice');
add_p('Filip', 'Karbowy', '3 wrz 1997', 'Polska', 'Ofensywny pomocnik', 17, '1,82m', 'prawa', 'Piast Gliwice');
add_p('Thierry', 'Gale', '1 maj 2002', 'Barbados', 'Lewy napastnik', 11, '1,68m', 'prawa', 'Piast Gliwice');
add_p('Jorge', 'Felix', '22 sie 1991', 'Hiszpania', 'Lewy napastnik', 7, '1,75m', 'prawa', 'Piast Gliwice');
add_p('Erik', 'Jirka', '19 wrz 1997', 'Słowacja', 'Prawy napastnik', 90, '1,83m', 'prawa', 'Piast Gliwice');
add_p('Andreas', 'Katsantonis', '16 lut 2000', 'Cypr', 'Środkowy napastnik', 70, '1,81m', 'prawa', 'Piast Gliwice');
add_p('Maciej', 'Rosołek', '2 wrz 2001', 'Polska', 'Środkowy napastnik', 39, '1,83m', 'prawa', 'Piast Gliwice');
add_p('Fabian', 'Piasecki', '4 maj 1995', 'Polska', 'Środkowy napastnik', 9, '1,86m', 'prawa', 'Piast Gliwice');
add_p('Maciej', 'Kikolski', '23 lut 2004', 'Polska', 'Bramkarz', 1, '1,92m', 'prawa', 'Radomiak Radom');
add_p('Wiktor', 'Koptas', '20 paź 2004', 'Polska', 'Bramkarz', 44, '1,88m', 'prawa', 'Radomiak Radom');
add_p('Marco', 'Burch', '19 paź 2000', 'Szwajcaria', 'Środkowy obrońca', 25, '1,86m', 'prawa', 'Radomiak Radom');
add_p('Steve', 'Kingue', '23 sty 2000', 'Kamerun', 'Środkowy obrońca', 74, '1,85m', 'prawa', 'Radomiak Radom');
add_p('Saad', 'Agouzoul', '10 sie 1997', 'Maroko', 'Środkowy obrońca', 5, '1,91m', 'lewa', 'Radomiak Radom');
add_p('Rahil', 'Mammadov', '24 lis 1995', 'Azerbejdżan', 'Środkowy obrońca', 4, '1,91m', 'prawa', 'Radomiak Radom');
add_p('Mateusz', 'Cichocki', '31 sty 1992', 'Polska', 'Środkowy obrońca', 16, '1,87m', 'prawa', 'Radomiak Radom');
add_p('Paulo', 'Henrique', '23 paź 1996', 'Portugalia', 'Lewy obrońca', 23, '1,82m', 'prawa', 'Radomiak Radom');
add_p('Kamil', 'Pestka', '22 sie 1998', 'Polska', 'Lewy obrońca', 33, '1,89m', 'lewa', 'Radomiak Radom');
add_p('Zié', 'Ouattara', '9 sty 2000', 'Wybrzeże Kości Słoniowej', 'Prawy obrońca', 24, '1,77m', 'prawa', 'Radomiak Radom');
add_p('Jan', 'Grzesik', '21 paź 1994', 'Polska', 'Prawy obrońca', 13, '1,78m', 'prawa', 'Radomiak Radom');
add_p('Bruno', 'Jordão', '12 paź 1998', 'Portugalia', 'Defensywny pomocnik', 6, '1,80m', 'prawa', 'Radomiak Radom');
add_p('Michał', 'Kaput', '18 lut 1998', 'Polska', 'Defensywny pomocnik', 28, '1,85m', 'obie', 'Radomiak Radom');
add_p('Christos', 'Donis', '9 paź 1994', 'Grecja', 'Defensywny pomocnik', 77, '1,84m', 'prawa', 'Radomiak Radom');
add_p('Francisco', 'Ramos', '10 kwi 1995', 'Portugalia', 'Środkowy pomocnik', 88, '1,81m', 'prawa', 'Radomiak Radom');
add_p('Roberto', 'Alves', '8 cze 1997', 'Szwajcaria, Portugalia', 'Ofensywny pomocnik', 10, '1,80m', 'lewa', 'Radomiak Radom');
add_p('Paulius', 'Golubickas', '19 sie 1999', 'Litwa', 'Ofensywny pomocnik', 8, '1,73m', 'obie', 'Radomiak Radom');
add_p('Rafael', 'Barbosa', '29 mar 1996', 'Portugalia', 'Ofensywny pomocnik', 19, '1,73m', 'prawa', 'Radomiak Radom');
add_p('Rafał', 'Wolski', '10 lis 1992', 'Polska', 'Ofensywny pomocnik', 27, '1,80m', 'prawa', 'Radomiak Radom');
add_p('Renat', 'Dadashov', '17 maj 1999', 'Azerbejdżan, Niemcy', 'Środkowy napastnik', 17, '1,88m', 'prawa', 'Radomiak Radom');
add_p('Abdoul', 'Tapsoba', '23 sie 2001', 'Burkina Faso', 'Środkowy napastnik', 15, '1,80m', 'prawa', 'Radomiak Radom');
add_p('Wojciech', 'Mazur', '26 kwi 2005', 'Polska', 'Pomocnik', 72, '1,80m', 'prawa', 'Radomiak Radom');
add_p('Adam', 'Woźniak', '6 kwi 2007', 'Polska', 'Pomocnik', 9, '1,80m', 'prawa', 'Radomiak Radom');
add_p('Tomasz', 'Krawczyk', '14 maj 2006', 'Polska', 'Pomocnik', 51, '1,80m', 'prawa', 'Radomiak Radom');
add_p('Mikołaj', 'Jankowski', '26 gru 2005', 'Polska', 'Pomocnik', 29, '1,80m', 'prawa', 'Radomiak Radom');
add_p('Rafał', 'Gikiewicz', '26 paź 1987', 'Polska', 'Bramkarz', 1, '1,90m', 'prawa', 'Widzew Łódź');
add_p('Mikołaj', 'Biegański', '5 kwi 2002', 'Polska', 'Bramkarz', 31, '1,88m', 'prawa', 'Widzew Łódź');
add_p('Jan', 'Krzywański', '10 mar 2003', 'Polska', 'Bramkarz', 33, '1,89m', 'prawa', 'Widzew Łódź');
add_p('Mateusz', 'Żyro', '28 paź 1998', 'Polska', 'Środkowy obrońca', 4, '1,90m', 'obie', 'Widzew Łódź');
add_p('Juan', 'Ibiza', '17 sie 1995', 'Hiszpania', 'Środkowy obrońca', 15, '1,87m', 'lewa', 'Widzew Łódź');
add_p('Luis', 'Silva', '18 lut 1999', 'Portugalia', 'Środkowy obrońca', 2, '1,86m', 'lewa', 'Widzew Łódź');
add_p('Samuel', 'Kozlovský', '19 lis 1999', 'Słowacja', 'Lewy obrońca', 3, '1,82m', 'lewa', 'Widzew Łódź');
add_p('Marcel', 'Krajewski', '21 paź 2004', 'Polska', 'Prawy obrońca', 91, '1,82m', 'prawa', 'Widzew Łódź');
add_p('Peter', 'Therkildsen', '13 cze 1998', 'Dania', 'Prawy obrońca', 16, '1,90m', 'prawa', 'Widzew Łódź');
add_p('Juljan', 'Shehu', '6 wrz 1998', 'Albania', 'Defensywny pomocnik', 6, '1,87m', 'prawa', 'Widzew Łódź');
add_p('Marek', 'Hanousek', '6 sie 1991', 'Czechy', 'Defensywny pomocnik', 25, '1,86m', 'prawa', 'Widzew Łódź');
add_p('Fran', 'Alvarez', '21 sty 1998', 'Hiszpania', 'Ofensywny pomocnik', 10, '1,78m', 'prawa', 'Widzew Łódź');
add_p('Jakub', 'Sypek', '7 kwi 2001', 'Polska', 'Ofensywny pomocnik', 77, '1,80m', 'prawa', 'Widzew Łódź');
add_p('Jakub', 'Łukowski', '25 maj 1996', 'Polska', 'Ofensywny pomocnik', 7, '1,72m', 'prawa', 'Widzew Łódź');
add_p('Bartłomiej', 'Pawłowski', '13 lis 1992', 'Polska', 'Ofensywny pomocnik', 19, '1,78m', 'prawa', 'Widzew Łódź');
add_p('Sebastian', 'Kerk', '17 kwi 1994', 'Niemcy', 'Ofensywny pomocnik', 37, '1,84m', 'lewa', 'Widzew Łódź');
add_p('Hilary', 'Gong', '10 paź 1998', 'Nigeria', 'Prawy napastnik', 8, '1,69m', 'prawa', 'Widzew Łódź');
add_p('Hubert', 'Sobol', '25 cze 2000', 'Polska', 'Środkowy napastnik', 17, '1,83m', 'prawa', 'Widzew Łódź');
add_p('Bartosz', 'Lewandowski', '25 sty 2007', 'Polska', 'Pomocnik', 78, '1,80m', 'prawa', 'Widzew Łódź');
add_p('Filip', 'Dąbrowski', '9 cze 2003', 'Polska', 'Pomocnik', 21, '1,80m', 'prawa', 'Widzew Łódź');
add_p('Paweł', 'Kwiatkowski', '5 maj 2005', 'Polska', 'Pomocnik', 30, '1,80m', 'prawa', 'Widzew Łódź');
add_p('Adam', 'Woźniak', '22 wrz 2004', 'Polska', 'Pomocnik', 80, '1,80m', 'prawa', 'Widzew Łódź');
add_p('Bartosz', 'Lewandowski', '2 lut 2007', 'Polska', 'Pomocnik', 52, '1,80m', 'prawa', 'Widzew Łódź');
add_p('Mikołaj', 'Jankowski', '28 wrz 2007', 'Polska', 'Pomocnik', 11, '1,80m', 'prawa', 'Widzew Łódź');
add_p('Bartosz', 'Lewandowski', '13 kwi 2004', 'Polska', 'Pomocnik', 39, '1,80m', 'prawa', 'Widzew Łódź');
add_p('Szymon', 'Weirauch', '5 mar 2004', 'Polska', 'Bramkarz', 1, '1,93m', 'prawa', 'Lechia Gdańsk');
add_p('Bogdan', 'Sarnavskyi', '29 sty 1995', 'Ukraina', 'Bramkarz', 29, '1,87m', 'prawa', 'Lechia Gdańsk');
add_p('Kacper', 'Gutowski', '15 cze 2006', 'Polska', 'Bramkarz', 81, '1,87m', 'prawa', 'Lechia Gdańsk');
add_p('Borys', 'Jesionowski', '5 cze 2007', 'Polska', 'Obrońca', 32, '-', 'prawa', 'Lechia Gdańsk');
add_p('Elias', 'Olsson', '23 kwi 2003', 'Szwecja', 'Środkowy obrońca', 3, '1,92m', 'lewa', 'Lechia Gdańsk');
add_p('Bujar', 'Pllana', '29 paź 2001', 'Kosowo', 'Środkowy obrońca', 44, '1,90m', 'prawa', 'Lechia Gdańsk');
add_p('Andrei', 'Chindriș', '12 sty 1999', 'Rumunia', 'Środkowy obrońca', 4, '1,91m', 'obie', 'Lechia Gdańsk');
add_p('Loup-Diwan', 'Gueho', '24 maj 2004', 'Francja', 'Środkowy obrońca', 94, '1,88m', 'prawa', 'Lechia Gdańsk');
add_p('Bartosz', 'Brylowski', '31 sty 2004', 'Polska', 'Środkowy obrońca', 24, '1,89m', 'lewa', 'Lechia Gdańsk');
add_p('Conrado', 'Conrado', '3 kwi 1997', 'Brazylia, Włochy', 'Lewy obrońca', 58, '1,73m', 'lewa', 'Lechia Gdańsk');
add_p('Miłosz', 'Kałahur', '29 cze 1999', 'Polska', 'Lewy obrońca', 23, '1,75m', 'lewa', 'Lechia Gdańsk');
add_p('Tomasz', 'Wójtowicz', '19 gru 2003', 'Polska', 'Prawy obrońca', 33, '1,80m', 'prawa', 'Lechia Gdańsk');
add_p('Ivan', 'Zhelizko', '12 lut 2001', 'Ukraina', 'Defensywny pomocnik', 5, '1,87m', 'prawa', 'Lechia Gdańsk');
add_p('Jan', 'Biegański', '4 gru 2002', 'Polska', 'Defensywny pomocnik', 2, '1,83m', 'lewa', 'Lechia Gdańsk');
add_p('Tomasz', 'Neugebauer', '8 maj 2003', 'Polska', 'Defensywny pomocnik', 99, '1,82m', 'prawa', 'Lechia Gdańsk');
add_p('Louis', 'D''Arrigo', '23 wrz 2001', 'Australia, Malta', 'Defensywny pomocnik', 16, '1,76m', 'prawa', 'Lechia Gdańsk');
add_p('Adam', 'Kardas', '23 sie 2006', 'Polska', 'Defensywny pomocnik', 42, '1,78m', 'prawa', 'Lechia Gdańsk');
add_p('Dominik', 'Piła', '6 maj 2001', 'Polska', 'Prawy pomocnik', 11, '1,87m', 'prawa', 'Lechia Gdańsk');
add_p('Marcel', 'Bajko', '6 cze 2006', 'Polska', 'Lewy pomocnik', 45, '1,74m', 'lewa', 'Lechia Gdańsk');
add_p('Bogdan', 'Viunnyk', '21 maj 2002', 'Ukraina', 'Ofensywny pomocnik', 9, '1,89m', 'obie', 'Lechia Gdańsk');
add_p('Rifet', 'Kapic', '3 lip 1995', 'Bośnia i Hercegowina', 'Ofensywny pomocnik', 8, '1,79m', 'lewa', 'Lechia Gdańsk');
add_p('Sergiy', 'Buletsa', '16 lut 1999', 'Ukraina', 'Ofensywny pomocnik', 26, '1,72m', 'prawa', 'Lechia Gdańsk');
add_p('Anton', 'Tsarenko', '17 cze 2004', 'Ukraina', 'Ofensywny pomocnik', 17, '1,62m', 'prawa', 'Lechia Gdańsk');
add_p('Karl', 'Wendt', '5 lip 2005', 'Szwecja', 'Ofensywny pomocnik', 6, '1,83m', 'prawa', 'Lechia Gdańsk');
add_p('Maksym', 'Khlan', '27 sty 2003', 'Ukraina', 'Lewy napastnik', 30, '1,73m', 'prawa', 'Lechia Gdańsk');
add_p('Kacper', 'Sezonienko', '23 mar 2003', 'Polska', 'Lewy napastnik', 79, '1,93m', 'prawa', 'Lechia Gdańsk');
add_p('Camilo', 'Mena', '1 paź 2002', 'Kolumbia', 'Prawy napastnik', 7, '1,75m', 'prawa', 'Lechia Gdańsk');
add_p('Tomas', 'Bobcek', '8 wrz 2001', 'Słowacja', 'Środkowy napastnik', 89, '1,87m', 'prawa', 'Lechia Gdańsk');
add_p('Michał', 'Głogowski', '4 sie 2005', 'Polska', 'Środkowy napastnik', 21, '1,90m', 'obie', 'Lechia Gdańsk');
add_p('Bartosz', 'Borkowski', '4 maj 2006', 'Polska', '', 77, '1,80m', 'prawa', 'Lechia Gdańsk');
add_p('Ivan', 'Brkic', '29 cze 1995', 'Chorwacja', 'Bramkarz', 40, '1,94m', 'prawa', 'Motor Lublin');
add_p('Gasper', 'Tratnik', '4 sty 2000', 'Słowenia', 'Bramkarz', 33, '1,91m', 'prawa', 'Motor Lublin');
add_p('Kacper', 'Rosa', '13 sie 1994', 'Polska', 'Bramkarz', 1, '1,91m', 'prawa', 'Motor Lublin');
add_p('Oskar', 'Jez', '7 sty 2007', 'Polska', 'Bramkarz', 45, '1,86m', 'prawa', 'Motor Lublin');
add_p('Igor', 'Bartnik', '30 cze 2005', 'Polska', 'Bramkarz', 51, '1,92m', 'prawa', 'Motor Lublin');
add_p('Bright', 'Ede', '18 lut 2007', 'Polska', 'Środkowy obrońca', 42, '1,93m', 'lewa', 'Motor Lublin');
add_p('Hervé', 'Matthys', '19 sty 1996', 'Belgia', 'Środkowy obrońca', 3, '1,86m', 'lewa', 'Motor Lublin');
add_p('Marek', 'Bartos', '13 paź 1996', 'Słowacja', 'Środkowy obrońca', 39, '1,93m', 'prawa', 'Motor Lublin');
add_p('Arkadiusz', 'Najemski', '12 sty 1996', 'Polska', 'Środkowy obrońca', 18, '1,82m', 'prawa', 'Motor Lublin');
add_p('Sebastian', 'Rudol', '21 lut 1995', 'Polska', 'Środkowy obrońca', 67, '1,85m', 'prawa', 'Motor Lublin');
add_p('Kamil', 'Kruk', '13 mar 2000', 'Polska', 'Środkowy obrońca', 74, '1,85m', 'prawa', 'Motor Lublin');
add_p('Arkadiusz', 'Murzacz', '23 cze 2006', 'Polska', 'Środkowy obrońca', 34, '-', 'prawa', 'Motor Lublin');
add_p('Filip', 'Luberecki', '25 kwi 2005', 'Polska', 'Lewy obrońca', 24, '1,72m', 'lewa', 'Motor Lublin');
add_p('Krystian', 'Palacz', '19 lip 2003', 'Polska', 'Lewy obrońca', 47, '1,80m', 'lewa', 'Motor Lublin');
add_p('Filip', 'Wójcik', '11 kwi 1997', 'Polska', 'Prawy obrońca', 17, '1,74m', 'prawa', 'Motor Lublin');
add_p('Paweł', 'Stolarski', '28 sty 1996', 'Polska', 'Prawy obrońca', 28, '1,81m', 'prawa', 'Motor Lublin');
add_p('Sergi', 'Samper', '20 sty 1995', 'Hiszpania', 'Defensywny pomocnik', 6, '1,81m', 'prawa', 'Motor Lublin');
add_p('Krzysztof', 'Kubica', '25 maj 2000', 'Polska', 'Defensywny pomocnik', 62, '1,93m', 'obie', 'Motor Lublin');
add_p('Jakub', 'Łabojko', '3 paź 1997', 'Polska', 'Defensywny pomocnik', 21, '1,79m', 'prawa', 'Motor Lublin');
add_p('Marcel', 'Gasior', '20 lis 1993', 'Polska', 'Defensywny pomocnik', 55, '1,85m', 'obie', 'Motor Lublin');
add_p('Kaan', 'Caliskaner', '3 lis 1999', 'Niemcy, Turcja', 'Środkowy pomocnik', 11, '1,94m', 'obie', 'Motor Lublin');
add_p('Patryk', 'Romanowski', '22 lut 2004', 'Polska', 'Lewy pomocnik', 41, '1,85m', 'lewa', 'Motor Lublin');
add_p('Bartosz', 'Wolski', '12 maj 1997', 'Polska', 'Ofensywny pomocnik', 68, '1,77m', 'prawa', 'Motor Lublin');
add_p('Christopher', 'Simon', '6 gru 1999', 'Senegal', 'Ofensywny pomocnik', 22, '1,85m', 'lewa', 'Motor Lublin');
add_p('Mathieu', 'Scalet', '1 kwi 1997', 'Francja, Polska', 'Ofensywny pomocnik', 37, '1,86m', 'obie', 'Motor Lublin');
add_p('Rafal', 'Krol', '16 sty 1989', 'Polska', 'Ofensywny pomocnik', 58, '1,83m', 'prawa', 'Motor Lublin');
add_p('Franciszek', 'Lewandowski', '23 maj 2008', 'Polska', 'Ofensywny pomocnik', 16, '1,77m', 'prawa', 'Motor Lublin');
add_p('Mbaye', 'Ndiaye', '10 paź 2003', 'Senegal', 'Lewy napastnik', 30, '1,78m', 'lewa', 'Motor Lublin');
add_p('Bradly van', 'Hoeven', '17 kwi 2000', 'Holandia', 'Lewy napastnik', 19, '1,74m', 'lewa', 'Motor Lublin');
add_p('Piotr', 'Ceglarz', '29 cze 1992', 'Polska', 'Lewy napastnik', 77, '1,82m', 'prawa', 'Motor Lublin');
add_p('Antonio', 'Sefer', '22 kwi 2000', 'Rumunia', 'Prawy napastnik', 7, '1,82m', 'lewa', 'Motor Lublin');
add_p('Michał', 'Król', '14 mar 2000', 'Polska', 'Prawy napastnik', 26, '1,73m', 'prawa', 'Motor Lublin');
add_p('Samuel', 'Mráz', '13 maj 1997', 'Słowacja', 'Środkowy napastnik', 90, '1,83m', 'prawa', 'Motor Lublin');
add_p('Jean-Kévin', 'Augustin', '16 cze 1997', 'Francja, Haiti', 'Środkowy napastnik', 97, '1,79m', 'prawa', 'Motor Lublin');
add_p('Kacper', 'Wełniak', '21 maj 2000', 'Polska', '', 9, '1,85m', 'obie', 'Motor Lublin');
add_p('Rafał', 'Mamla', '22 gru 2003', 'Polska', 'Bramkarz', 87, '1,95m', 'prawa', 'Korona Kielce');
add_p('Xavier', 'Dziekoński', '6 paź 2003', 'Polska', 'Bramkarz', 1, '1,88m', 'prawa', 'Korona Kielce');
add_p('Marcel', 'Zapytowski', '8 sty 2001', 'Polska', 'Bramkarz', 74, '1,89m', 'prawa', 'Korona Kielce');
add_p('Michał', 'Niedbała', '10 kwi 2006', 'Polska', 'Bramkarz', 47, '1,93m', 'prawa', 'Korona Kielce');
add_p('Michał', 'Mikielewicz', '26 wrz 2008', 'Polska', 'Bramkarz', 12, '1,87m', 'prawa', 'Korona Kielce');
add_p('Pau', 'Resta', '14 lis 2000', 'Hiszpania', 'Środkowy obrońca', 5, '1,85m', 'lewa', 'Korona Kielce');
add_p('Bartłomiej', 'Smolarczyk', '2 lip 2003', 'Polska', 'Środkowy obrońca', 24, '1,91m', 'prawa', 'Korona Kielce');
add_p('Marcel', 'Pięczek', '11 gru 2000', 'Polska', 'Środkowy obrońca', 6, '1,85m', 'lewa', 'Korona Kielce');
add_p('Milosz', 'Trojak', '5 maj 1994', 'Polska', 'Środkowy obrońca', 59, '1,91m', 'prawa', 'Korona Kielce');
add_p('Konstantinos', 'Sotiriou', '21 cze 1996', 'Cypr', 'Środkowy obrońca', 44, '1,90m', 'prawa', 'Korona Kielce');
add_p('Dominick', 'Zator', '18 wrz 1994', 'Kanada, Polska', 'Środkowy obrońca', 2, '1,88m', 'prawa', 'Korona Kielce');
add_p('Piotr', 'Malarczyk', '1 sie 1991', 'Polska', 'Środkowy obrońca', 4, '1,89m', 'prawa', 'Korona Kielce');
add_p('Igor', 'Kośmicki', '18 lis 2002', 'Polska', 'Środkowy obrońca', 15, '1,90m', 'prawa', 'Korona Kielce');
add_p('Martin', 'Remacle', '16 maj 1997', 'Belgia', 'Defensywny pomocnik', 8, '1,76m', 'prawa', 'Korona Kielce');
add_p('Yoav', 'Hofmayster', '25 gru 2000', 'Izrael', 'Defensywny pomocnik', 6, '1,80m', 'prawa', 'Korona Kielce');
add_p('Łukasz', 'Kamiński', '17 lis 2005', 'Polska', 'Pomocnik', 73, '1,80m', 'prawa', 'Korona Kielce');
add_p('Andrzej', 'Wójcik', '8 kwi 2006', 'Polska', 'Pomocnik', 38, '1,80m', 'prawa', 'Korona Kielce');
add_p('Mikołaj', 'Jankowski', '13 paź 2005', 'Polska', 'Pomocnik', 72, '1,80m', 'prawa', 'Korona Kielce');
add_p('Tomasz', 'Krawczyk', '17 paź 2005', 'Polska', 'Pomocnik', 62, '1,80m', 'prawa', 'Korona Kielce');
add_p('Adam', 'Woźniak', '10 sty 2004', 'Polska', 'Pomocnik', 63, '1,80m', 'prawa', 'Korona Kielce');
add_p('Paweł', 'Kwiatkowski', '1 maj 2006', 'Polska', 'Pomocnik', 95, '1,80m', 'prawa', 'Korona Kielce');
add_p('Szymon', 'Kozłowski', '20 paź 2003', 'Polska', 'Pomocnik', 81, '1,80m', 'prawa', 'Korona Kielce');
add_p('Łukasz', 'Kamiński', '19 gru 2004', 'Polska', 'Pomocnik', 89, '1,80m', 'prawa', 'Korona Kielce');
add_p('Szymon', 'Kozłowski', '2 lip 2006', 'Polska', 'Pomocnik', 54, '1,80m', 'prawa', 'Korona Kielce');
add_p('Mikołaj', 'Jankowski', '14 kwi 2007', 'Polska', 'Pomocnik', 52, '1,80m', 'prawa', 'Korona Kielce');
add_p('Dawid', 'Kudła', '21 mar 1992', 'Polska', 'Bramkarz', 1, '1,90m', 'prawa', 'GKS Katowice');
add_p('Rafał', 'Strączek', '12 lut 1999', 'Polska', 'Bramkarz', 32, '1,89m', 'prawa', 'GKS Katowice');
add_p('Przemyslaw', 'Peksa', '12 mar 2002', 'Polska', 'Bramkarz', 12, '1,86m', 'prawa', 'GKS Katowice');
add_p('Patryk', 'Szczuka', '31 sty 2002', 'Polska', '', 33, '1,89m', 'prawa', 'GKS Katowice');
add_p('Märten', 'Kuusk', '5 kwi 1996', 'Estonia', 'Środkowy obrońca', 2, '1,82m', 'prawa', 'GKS Katowice');
add_p('Lukas', 'Klemenz', '24 wrz 1995', 'Polska', 'Środkowy obrońca', 6, '1,91m', 'prawa', 'GKS Katowice');
add_p('Alan', 'Czerwiński', '2 lut 1993', 'Polska', 'Środkowy obrońca', 30, '1,81m', 'prawa', 'GKS Katowice');
add_p('Arkadiusz', 'Jędrych', '27 maj 1992', 'Polska', 'Środkowy obrońca', 4, '1,91m', 'prawa', 'GKS Katowice');
add_p('Aleksander', 'Komor', '24 cze 1994', 'Polska', 'Środkowy obrońca', 14, '1,90m', 'prawa', 'GKS Katowice');
add_p('Bartosz', 'Jaroszek', '17 lut 1994', 'Polska', 'Środkowy obrońca', 13, '1,89m', 'prawa', 'GKS Katowice');
add_p('Łukasz', 'Trepka', '26 gru 2006', 'Polska', 'Środkowy obrońca', 25, '1,82m', 'prawa', 'GKS Katowice');
add_p('Jakub', 'Kaduk', '26 lut 2004', 'Polska', 'Środkowy obrońca', 26, '1,86m', 'lewa', 'GKS Katowice');
add_p('Mateusz', 'Kowalczyk', '16 kwi 2004', 'Polska', 'Defensywny pomocnik', 77, '1,81m', 'obie', 'GKS Katowice');
add_p('Oskar', 'Repka', '3 sty 1999', 'Polska', 'Defensywny pomocnik', 5, '1,90m', 'prawa', 'GKS Katowice');
add_p('Sebastian', 'Milewski', '30 kwi 1998', 'Polska', 'Defensywny pomocnik', 22, '1,75m', 'prawa', 'GKS Katowice');
add_p('Bartosz', 'Baranowicz', '11 sty 2003', 'Polska', 'Defensywny pomocnik', 21, '1,75m', 'prawa', 'GKS Katowice');
add_p('Marcin', 'Wasielewski', '23 sie 1994', 'Polska', 'Prawy pomocnik', 23, '1,72m', 'prawa', 'GKS Katowice');
add_p('Konrad', 'Gruszkowski', '27 sty 2001', 'Polska', 'Prawy pomocnik', 24, '1,83m', 'prawa', 'GKS Katowice');
add_p('Adrian', 'Danek', '1 sie 1994', 'Polska', 'Prawy pomocnik', 20, '1,80m', 'prawa', 'GKS Katowice');
add_p('Borja', 'Galán', '26 kwi 1993', 'Hiszpania', 'Lewy pomocnik', 8, '1,82m', 'prawa', 'GKS Katowice');
add_p('Grzegorz', 'Rogala', '12 paź 1995', 'Polska', 'Lewy pomocnik', 16, '1,83m', 'lewa', 'GKS Katowice');
add_p('Dawid', 'Drachal', '31 sty 2005', 'Polska', 'Ofensywny pomocnik', 18, '1,82m', 'obie', 'GKS Katowice');
add_p('Bartosz', 'Nowak', '25 sie 1993', 'Polska', 'Ofensywny pomocnik', 27, '1,80m', 'prawa', 'GKS Katowice');
add_p('Jakub', 'Antczak', '29 kwi 2004', 'Polska', 'Ofensywny pomocnik', 88, '1,73m', 'prawa', 'GKS Katowice');
add_p('Adrian', 'Błąd', '16 kwi 1991', 'Polska', 'Ofensywny pomocnik', 11, '1,65m', 'obie', 'GKS Katowice');
add_p('Mateusz', 'Marzec', '13 sie 1994', 'Polska', 'Ofensywny pomocnik', 17, '1,78m', 'prawa', 'GKS Katowice');
add_p('Shun', 'Shibata', '15 cze 1997', 'Japonia', 'Ofensywny pomocnik', 54, '1,65m', 'prawa', 'GKS Katowice');
add_p('Mateusz', 'Mak', '14 lis 1991', 'Polska', 'Ofensywny pomocnik', 10, '1,78m', 'prawa', 'GKS Katowice');
add_p('Alan', 'Bród', '9 sie 2004', 'Polska', 'Ofensywny pomocnik', 28, '1,77m', 'prawa', 'GKS Katowice');
add_p('Filip', 'Szymczak', '6 maj 2002', 'Polska', 'Prawy napastnik', 19, '1,87m', 'prawa', 'GKS Katowice');
add_p('Sebastian', 'Bergier', '20 gru 1999', 'Polska', 'Środkowy napastnik', 7, '1,86m', 'prawa', 'GKS Katowice');
add_p('Adam', 'Zrelak', '5 maj 1994', 'Słowacja', 'Środkowy napastnik', 99, '1,83m', 'lewa', 'GKS Katowice');
add_p('Jakub', 'Arak', '2 kwi 1995', 'Polska', 'Środkowy napastnik', 71, '1,83m', 'prawa', 'GKS Katowice');
add_p('Jakub', 'Mądrzyk', '4 gru 2003', 'Polska', 'Bramkarz', 39, '1,91m', 'prawa', 'Stal Mielec');
add_p('Konrad', 'Jałocha', '9 maj 1991', 'Polska', 'Bramkarz', 13, '2,01m', 'prawa', 'Stal Mielec');
add_p('Karol', 'Dybowski', '12 cze 1997', 'Polska', 'Bramkarz', 12, '1,86m', 'prawa', 'Stal Mielec');
add_p('Kevin', 'Szurlej', '20 lip 2007', 'Polska', 'Bramkarz', 70, '1,90m', 'prawa', 'Stal Mielec');
add_p('Bert', 'Esselink', '16 sie 1999', 'Holandia', 'Środkowy obrońca', 3, '1,91m', 'prawa', 'Stal Mielec');
add_p('Marvin', 'Senger', '6 sty 2000', 'Niemcy', 'Środkowy obrońca', 15, '1,93m', 'lewa', 'Stal Mielec');
add_p('Marco', 'Ehmann', '3 sie 2000', 'Rumunia, Niemcy', 'Środkowy obrońca', 5, '1,89m', 'obie', 'Stal Mielec');
add_p('Mateusz', 'Matras', '23 sty 1991', 'Polska', 'Środkowy obrońca', 21, '1,93m', 'prawa', 'Stal Mielec');
add_p('Kamil', 'Pajnowski', '28 sty 1998', 'Polska', 'Środkowy obrońca', 4, '1,86m', 'lewa', 'Stal Mielec');
add_p('Alvis', 'Jaunzems', '16 cze 1999', 'Łotwa', 'Prawy obrońca', 27, '1,79m', 'prawa', 'Stal Mielec');
add_p('Matthew', 'Guillaumier', '9 kwi 1998', 'Malta, Anglia', 'Defensywny pomocnik', 6, '1,83m', 'prawa', 'Stal Mielec');
add_p('Karol', 'Knap', '12 wrz 2001', 'Polska', 'Defensywny pomocnik', 20, '1,80m', 'lewa', 'Stal Mielec');
add_p('Adrian', 'Bukowski', '18 mar 2003', 'Polska', 'Defensywny pomocnik', 33, '1,88m', 'prawa', 'Stal Mielec');
add_p('Piotr', 'Wlazło', '3 cze 1989', 'Polska', 'Defensywny pomocnik', 18, '1,84m', 'prawa', 'Stal Mielec');
add_p('Pyry', 'Hannola', '21 paź 2001', 'Finlandia', 'Środkowy pomocnik', 26, '1,85m', 'lewa', 'Stal Mielec');
add_p('Sergiy', 'Krykun', '22 wrz 1996', 'Ukraina', 'Prawy pomocnik', 44, '1,75m', 'prawa', 'Stal Mielec');
add_p('Dawid', 'Zieba', '25 sty 2005', 'Polska', 'Prawy pomocnik', 77, '1,84m', 'obie', 'Stal Mielec');
add_p('Krzysztof', 'Wołkowicz', '12 wrz 1994', 'Polska', 'Lewy pomocnik', 11, '1,80m', 'lewa', 'Stal Mielec');
add_p('Krystian', 'Getinger', '29 sie 1988', 'Polska', 'Lewy pomocnik', 23, '1,88m', 'lewa', 'Stal Mielec');
add_p('Fryderyk', 'Gerbowski', '17 sty 2003', 'Polska', 'Ofensywny pomocnik', 32, '1,81m', 'obie', 'Stal Mielec');
add_p('Kōki', 'Hinokio', '26 lut 2001', 'Japonia', 'Ofensywny pomocnik', 53, '1,65m', 'prawa', 'Stal Mielec');
add_p('Damian', 'Kądzior', '16 cze 1992', 'Polska', 'Ofensywny pomocnik', 92, '1,74m', 'lewa', 'Stal Mielec');
add_p('Dawid', 'Tkacz', '25 sty 2005', 'Polska', 'Ofensywny pomocnik', 19, '1,81m', 'lewa', 'Stal Mielec');
add_p('Maciej', 'Domanski', '5 wrz 1990', 'Polska', 'Ofensywny pomocnik', 10, '1,67m', 'prawa', 'Stal Mielec');
add_p('Ivan', 'Cavaleiro', '18 paź 1993', 'Angola, Portugalia', 'Lewy napastnik', 14, '1,75m', 'prawa', 'Stal Mielec');
add_p('Robert', 'Dadok', '24 gru 1996', 'Polska', 'Prawy napastnik', 96, '1,84m', 'prawa', 'Stal Mielec');
add_p('Lukasz', 'Wolsztynski', '8 gru 1994', 'Polska', 'Środkowy napastnik', 25, '1,83m', 'prawa', 'Stal Mielec');
add_p('Ravve', 'Assayag', '1 maj 2001', 'Izrael, Hiszpania', 'Środkowy napastnik', 9, '1,86m', 'obie', 'Stal Mielec');
add_p('Kewin', 'Komar', '26 lip 2003', 'Polska', 'Bramkarz', 1, '1,93m', 'lewa', 'Puszcza Niepołomice');
add_p('Michał', 'Perchel', '27 cze 2007', 'Polska', 'Bramkarz', 31, '1,92m', 'prawa', 'Puszcza Niepołomice');
add_p('Roman', 'Yakuba', '23 kwi 2001', 'Ukraina', 'Środkowy obrońca', 3, '1,93m', 'lewa', 'Puszcza Niepołomice');
add_p('Artur', 'Crăciun', '29 cze 1998', 'Mołdawia, Rumunia', 'Środkowy obrońca', 22, '1,93m', 'prawa', 'Puszcza Niepołomice');
add_p('Dawid', 'Szymonowicz', '7 lip 1995', 'Polska', 'Środkowy obrońca', 4, '1,85m', 'prawa', 'Puszcza Niepołomice');
add_p('Łukasz', 'Sołowiej', '11 paź 1988', 'Polska', 'Środkowy obrońca', 27, '1,89m', 'prawa', 'Puszcza Niepołomice');
add_p('Michal', 'Siplak', '2 lut 1996', 'Słowacja', 'Lewy obrońca', 18, '1,84m', 'lewa', 'Puszcza Niepołomice');
add_p('Ioan-Calin', 'Revenco', '26 cze 2000', 'Mołdawia, Rumunia', 'Prawy obrońca', 67, '1,76m', 'prawa', 'Puszcza Niepołomice');
add_p('Piotr', 'Mroziński', '24 sie 1992', 'Polska', 'Prawy obrońca', 8, '1,81m', 'prawa', 'Puszcza Niepołomice');
add_p('Jani', 'Atanasov', '31 paź 1999', 'Macedonia Północna, Bułgaria', 'Defensywny pomocnik', 6, '1,87m', 'prawa', 'Puszcza Niepołomice');
add_p('Jakub', 'Serafin', '25 maj 1996', 'Polska', 'Defensywny pomocnik', 14, '1,81m', 'prawa', 'Puszcza Niepołomice');
add_p('Konrad', 'Stępień', '7 mar 1993', 'Polska', 'Defensywny pomocnik', 5, '1,85m', 'prawa', 'Puszcza Niepołomice');
add_p('Mateusz', 'Radecki', '2 kwi 1993', 'Polska', 'Defensywny pomocnik', 17, '1,87m', 'prawa', 'Puszcza Niepołomice');
add_p('Georgiy', 'Zhukov', '19 lis 1994', 'Kazachstan, Belgia', 'Środkowy pomocnik', 88, '1,72m', 'prawa', 'Puszcza Niepołomice');
add_p('Dawid', 'Abramowicz', '16 maj 1991', 'Polska', 'Lewy pomocnik', 33, '1,86m', 'lewa', 'Puszcza Niepołomice');
add_p('Jakov', 'Blagaic', '8 lut 2000', 'Chorwacja', 'Ofensywny pomocnik', 24, '1,73m', 'prawa', 'Puszcza Niepołomice');
add_p('Hubert', 'Tomalski', '19 sie 1993', 'Polska', 'Ofensywny pomocnik', 10, '1,73m', 'obie', 'Puszcza Niepołomice');
add_p('Antoni', 'Klimek', '4 sie 2002', 'Polska', 'Lewy napastnik', 7, '1,76m', 'obie', 'Puszcza Niepołomice');
add_p('Mateusz', 'Cholewiak', '5 lut 1990', 'Polska', 'Lewy napastnik', 34, '1,83m', 'lewa', 'Puszcza Niepołomice');
add_p('Szymon', 'Kozłowski', '18 kwi 2007', 'Polska', 'Pomocnik', 42, '1,80m', 'prawa', 'Puszcza Niepołomice');
add_p('Michał', 'Zieliński', '4 paź 2005', 'Polska', 'Pomocnik', 92, '1,80m', 'prawa', 'Puszcza Niepołomice');
add_p('Jakub', 'Szymański', '7 sty 2005', 'Polska', 'Pomocnik', 79, '1,80m', 'prawa', 'Puszcza Niepołomice');
add_p('Łukasz', 'Kamiński', '4 lip 2004', 'Polska', 'Pomocnik', 68, '1,80m', 'prawa', 'Puszcza Niepołomice');
add_p('Filip', 'Dąbrowski', '7 mar 2007', 'Polska', 'Pomocnik', 90, '1,80m', 'prawa', 'Puszcza Niepołomice');
add_p('Łukasz', 'Kamiński', '25 sty 2005', 'Polska', 'Pomocnik', 12, '1,80m', 'prawa', 'Puszcza Niepołomice');
COMMIT;
END;
/

add_p('Jan', 'Kowalski', '12 mar 2002', 'Polska', 'Pomocnik', 88, '1,82m', 'prawa', 'Jagiellonia Białystok');
add_p('Adam', 'Nowak', '05 lip 2001', 'Polska', 'Obrońca', 77, '1,85m', 'prawa', 'Śląsk Wrocław');
add_p('Piotr', 'Wisniewski', '22 wrz 2003', 'Polska', 'Napastnik', 99, '1,88m', 'prawa', 'Legia Warszawa');
add_p('Mateusz', 'Wojcik', '14 lis 2000', 'Polska', 'Bramkarz', 35, '1,90m', 'lewa', 'Pogoń Szczecin');
add_p('Krzysztof', 'Kaminski', '08 sty 1999', 'Polska', 'Pomocnik', 44, '1,79m', 'prawa', 'Lech Poznań');
add_p('Michal', 'Lewandowski', '30 kwi 2004', 'Polska', 'Obrońca', 55, '1,83m', 'lewa', 'Górnik Zabrze');
add_p('Tomasz', 'Zielinski', '17 lut 2002', 'Polska', 'Napastnik', 22, '1,86m', 'prawa', 'Raków Częstochowa');
add_p('Pawel', 'Szymanski', '09 cze 2001', 'Polska', 'Pomocnik', 66, '1,81m', 'prawa', 'Zagłębie Lubin');
add_p('Jakub', 'Dabrowski', '25 sie 2003', 'Polska', 'Obrońca', 13, '1,84m', 'prawa', 'Widzew Łódź');
add_p('Szymon', 'Kozlowski', '02 gru 2000', 'Polska', 'Napastnik', 19, '1,87m', 'lewa', 'Piast Gliwice');

